
        // CƠ SỞ DỮ LIỆU DỊCH VỤ CHI TIẾT CHUẨN Y KHOA
        const SERVICES_DATABASE = [
            // FACIAL (1) & (2)
            { id: 1, name: "Full facelift (deep plane facelift) - Căng da mặt tầng sâu toàn diện", price: 1600, category: "facial" },
            { id: 2, name: "Mini facelift (deep plane facelift) - Căng da mặt tầng sâu bán phần", price: 1000, category: "facial" },
            { id: 3, name: "Neck lift - Căng da & cơ trẻ hóa vùng cổ", price: 700, category: "facial" },
            { id: 4, name: "Dermal fat grafting into the nasolabial folds - Cấy mỡ tự thân rãnh cười", price: 1300, category: "facial" },
            { id: 5, name: "Double chin liposuction - Hút mỡ nọng cằm tạo viền hàm", price: 1300, category: "facial" },
            { id: 6, name: "Lower eyelid - Tạo hình thẩm mỹ mí dưới", price: 450, category: "facial" },
            { id: 7, name: "Upper eyelid - Tạo hình thẩm mỹ mí trên", price: 450, category: "facial" },
            { id: 8, name: "Lower eyelid with fat grafting - Tạo hình mí dưới kết hợp cấy ghép mỡ", price: 800, category: "facial" },
            { id: 9, name: "Upper eyelid with fat grafting - Tạo hình mí trên kết hợp cấy ghép mỡ", price: 800, category: "facial" },
            { id: 10, name: "Eyebrow lift - Treo cung chân mày trẻ hóa vùng mắt", price: 450, category: "facial" },
            { id: 11, name: "Outer corner eye - Tạo hình góc mắt ngoài (mở rộng đuôi mắt)", price: 300, category: "facial" },
            { id: 12, name: "Inter corner eye - Tạo hình góc mắt trong (mở rộng khóe mắt)", price: 300, category: "facial" },
            { id: 13, name: "Eye enlargement - Phẫu thuật mở rộng góc mắt toàn diện", price: 450, category: "facial" },
            { id: 14, name: "Fox eye - Tạo hình mắt cáo quyến rũ", price: 450, category: "facial" },
            { id: 15, name: "Philtrum reduction - Thu ngắn nhân trung tạo tỉ lệ vàng", price: 450, category: "facial" },
            { id: 16, name: "Create deep philtrum / Create lip corners - Tạo hình nhân trung sâu / tạo khóe môi cười", price: 300, category: "facial" },
            { id: 17, name: "Lip lift / lip cut - Thu mỏng môi / nâng cơ môi thẩm mỹ", price: 450, category: "facial" },
            { id: 18, name: "Create dimples - Tạo hình má lúm đồng tiền xinh xắn", price: 200, category: "facial" },
            { id: 19, name: "Forehead lift / forehead reduction - Hạ đường chân tóc / Căng da trán xóa nhăn", price: 2000, category: "facial" },
            { id: 20, name: "Forehead lift combine forehead reduction - Combo căng da trán kết hợp hạ đường chân tóc", price: 3000, category: "facial" },
            { id: 21, name: "Forehead implant - Độn trán thẩm mỹ (tạo độ nhô đầy đặn)", price: 2500, category: "facial" },
            { id: 22, name: "Cheek fat removal - Phẫu thuật lấy túi mỡ má trong thon gọn mặt", price: 600, category: "facial" },
            { id: 23, name: "Facial fat grafting - Cấy mỡ tự thân trẻ hóa toàn bộ gương mặt", price: 1000, category: "facial" },
            { id: 24, name: "Rhinoplasty Lasik USA - Nâng mũi cấu trúc chất liệu Lasik cao cấp", price: 1800, category: "facial" },
            { id: 25, name: "Rhinoplasty Nanoform (goretex) - Nâng mũi cấu trúc Nanoform siêu bám dính", price: 2500, category: "facial" },
            { id: 26, name: "Rhinoplasty Surgiform (goretex) - Nâng mũi cấu trúc Surgiform sinh học", price: 3200, category: "facial" },
            { id: 27, name: "Dermal fat grafting into the nose - Cấy ghép mỡ tự thân tạo hình sống mũi", price: 1300, category: "facial" },
            { id: 28, name: "Nose wing reduction - Thu gọn cánh mũi (cắt / cuộn cánh mũi)", price: 300, category: "facial" },
            { id: 29, name: "Chin implant cartilage USA - Độn cằm sụn silicon cao cấp nhập khẩu Mỹ", price: 1600, category: "facial" },
            { id: 30, name: "Chin implant cartilage Korea - Độn cằm sụn sinh học cao cấp nhập khẩu Hàn Quốc", price: 1300, category: "facial" },
            { id: 31, name: "Jaw reduction - Phẫu thuật hạ xương gò má / gọt hàm thon gọn", price: 3500, category: "facial" },
            { id: 32, name: "Chin reduction - Phẫu thuật trượt cằm / thu nhỏ xương cằm", price: 3000, category: "facial" },
            { id: 33, name: "Cheekbone reduction - Phẫu thuật hạ / ép xương gò má cao", price: 3500, category: "facial" },
            { id: 34, name: "Filler Korea (Chất làm đầy nhập khẩu Hàn Quốc cao cấp) - Đơn vị: 1cc", price: 200, category: "facial" },
            { id: 35, name: "Filler USA (Chất làm đầy nhập khẩu Hoa Kỳ cao cấp) - Đơn vị: 1cc", price: 500, category: "facial" },
            { id: 36, name: "Botox (Xóa nhăn, thon gọn hàm chính hãng) - Đơn vị: units", price: 300, category: "facial" },

            // BODY (1) & (2)
            { id: 37, name: "Endoscopic Plasma Breast Augmentation (Nano Motiva) - Nâng ngực nội soi Plasma túi Motiva", price: 3500, category: "body" },
            { id: 38, name: "Endoscopic Plasma Breast Augmentation (Mentor) - Nâng ngực nội soi Plasma túi Mentor cao cấp", price: 3800, category: "body" },
            { id: 39, name: "Endoscopic Plasma Breast Augmentation (Nano Chip) - Nâng ngực nội soi Plasma túi Motiva Ergonomix (có chip)", price: 4000, category: "body" },
            { id: 40, name: "Nano Plasma No-Touch Breast Augmentation - Nâng ngực không chạm kỹ thuật số Nano Plasma", price: 4200, category: "body" },
            { id: 41, name: "Endoscopic Plasma Breast Augmentation (Nano Ergonomic) - Nâng ngực nội soi túi sinh học thế hệ mới", price: 4600, category: "body" },
            { id: 42, name: "AU-Hybrid No-Touch Breast Augmentation - Nâng ngực Hybrid siêu tự nhiên (Kết hợp túi độn & cấy mỡ tự thân)", price: 5000, category: "body" },
            { id: 43, name: "3D Nano Plasma No-Touch Breast Augmentation - Nâng ngực không chạm 3D đẳng cấp cao nhất", price: 6500, category: "body" },
            { id: 44, name: "Nipple / Areola Reduction - Thu nhỏ đầu vú (núm vú) / Thu gọn quầng vú", price: 1000, category: "body" },
            { id: 45, name: "Breast Lift (Grade 2 Ptosis) - Treo ngực sa trễ cấp độ nhẹ (Cấp độ 2)", price: 1500, category: "body" },
            { id: 46, name: "Breast Lift (Grade 3-4 Ptosis) - Treo ngực sa trễ trung bình & nặng (Cấp độ 3-4)", price: 1800, category: "body" },
            { id: 47, name: "Breast Lift (Grade 5 Ptosis) - Treo ngực sa trễ đặc biệt nặng (Cấp độ 5)", price: 2200, category: "body" },
            { id: 48, name: "Arm liposuction - Hút mỡ bắp tay thon gọn phẳng lỳ", price: 1500, category: "body" },
            { id: 49, name: "Arm Liposuction (Combined with Major Surgery) - Hút mỡ bắp tay (Kết hợp cùng ca phẫu thuật lớn khác)", price: 1200, category: "body" },
            { id: 50, name: "Back Liposuction - Hút mỡ vùng lưng phẳng gọn mượt mà", price: 1700, category: "body" },
            { id: 51, name: "Back Liposuction (Combined with Major Surgery) - Hút mỡ vùng lưng (Kết hợp cùng ca đại phẫu khác)", price: 1500, category: "body" },
            { id: 52, name: "Thigh Liposuction - Hút mỡ vùng đùi săn chắc quyến rũ", price: 2000, category: "body" },
            { id: 53, name: "Thigh Liposuction (Combined with Major Surgery) - Hút mỡ vùng đùi (Kết hợp cùng ca đại phẫu khác)", price: 1700, category: "body" },
            { id: 54, name: "Tummy Tuck with Umbilical Repositioning - Tạo hình thành bụng (Tummy Tuck) kết hợp chuyển rốn thẩm mỹ", price: 2000, category: "body" },
            { id: 55, name: "Abdominal Liposuction (Upper, Lower, Flanks) - Hút mỡ bụng toàn diện (Bụng trên, bụng dưới, hai bên hông eo)", price: 2500, category: "body" },
            { id: 56, name: "Abdominoplasty with Liposuction - Tạo hình thành bụng toàn thể kết hợp hút mỡ eo hông", price: 3500, category: "body" },
            { id: 57, name: "Arm lift - Phẫu thuật căng da nội soi bắp tay chảy xệ", price: 1500, category: "body" },
            { id: 58, name: "Arm liposuction & lift - Combo hút mỡ kết hợp phẫu thuật căng da bắp tay", price: 1800, category: "body" },
            { id: 59, name: "Thigh lift - Phẫu thuật căng da thu gọn vùng đùi", price: 2200, category: "body" },
            { id: 60, name: "Thigh liposuction & lift - Combo hút mỡ kết hợp phẫu thuật căng da vùng đùi", price: 2700, category: "body" },
            { id: 61, name: "Fat Grafting to Buttocks - Hút mỡ cấy mỡ tự thân tạo hình vòng ba (Mông)", price: 1500, category: "body" },
            { id: 62, name: "Buttock Implants (Motiva) - Phẫu thuật nâng mông bằng túi độn Motiva chuyên dụng", price: 4300, category: "body" }
        ];

        // TỪ ĐIỂN ĐA NGÔN NGỮ (Sử dụng dịch giao diện mượt mà)
        const DICTIONARY = {
    vi: {
        nav_home: "Trang Chủ",
        nav_about: "Giới Thiệu",
        nav_services: "Dịch Vụ",
        nav_before_after: "Trước Sau",
        nav_price: "Bảng Giá",
        nav_faq: "FAQ",
        nav_contact: "Liên Hệ",
        book_now: "ĐẶT LỊCH HẸN",
        hero_badge: "Viện Thẩm Mỹ Chuẩn Y Khoa Quốc Tế",
        hero_title: "Định Hình <span class='text-transparent bg-clip-text bg-gradient-to-r from-brand-gold to-amber-600 text-glow-gold'>Vẻ Đẹp Hoàn Mỹ</span> <br class='hidden sm:inline'> Với Công Nghệ Hiện Đại",
        hero_desc: "Đường nét hài hòa sang trọng dưới bàn tay chuyên gia thẩm mỹ bậc cao <strong class='text-brand-gold font-bold'>Dr. Tùng Dương</strong>. Cam kết an toàn tuyệt đối, mang lại dáng vẻ cân đối chuẩn tỉ lệ vàng cá nhân.",
        stats_med: "Chuẩn Y Khoa",
        stats_happy: "Khách Hài Lòng",
        stats_exp: "Năm Kinh Nghiệm",
        btn_price: "Xem Bảng Giá Chi Tiết",
        btn_whatsapp: "Tư vấn WhatsApp ngay",
        dr_title: "BÁC SĨ THẨM MỸ",
        dr_quote: "“Kiến tạo vẻ đẹp hoàn hảo bằng sự tận tâm, tinh tế và chuẩn y khoa.”",
        badge_cert_title: "Chất lượng",
        badge_cert_desc: "Bộ Y Tế Cấp Phép",
        stat_1: "Khách Hàng Đã Phẫu Thuật",
        stat_2: "Đánh Giá Phản Hồi",
        stat_3: "Hoạt Động Chuyên Môn",
        stat_4: "Tư Vấn Chăm Sóc Hậu Phẫu",
        about_badge_top: "Chất Lượng Thẩm Mỹ",
        about_badge_bottom: "Tỉ lệ vàng cho từng khuôn diện Á Đông",
        about_tag: "VỀ CHÚNG TÔI",
        about_title: "Điều Trị Bằng Sự Tận Tâm,<br>Y Đức & Nguyên Tắc Nhân Văn",
        about_desc: "Tại viện thẩm mỹ của chúng tôi, mỗi ca phẫu thuật không chỉ đơn thuần là sự tác động y học, mà còn là một tác phẩm nghệ thuật điêu khắc hoàn chỉnh. <strong>Dr. Tùng Dương</strong> luôn áp dụng tôn chỉ kiến tạo vẻ đẹp tự nhiên hài hòa với từng góc nhìn cá nhân, tuyệt đối không rập khuôn mẫu số chung.",
        feature_1_title: "Vật Liệu Cao Cấp",
        feature_1_desc: "Sử dụng vật liệu cấy ghép cao cấp chính hãng nhập khẩu được FDA công nhận an toàn.",
        feature_2_title: "Vô Trùng Khép Kín",
        feature_2_desc: "Phòng mổ đạt chuẩn y khoa quốc tế, vô trùng tuyệt đối hạn chế nhiễm trùng tối đa.",
        feature_3_title: "Bác Sĩ Cùng Ê Kíp",
        feature_3_desc: "Bác sĩ cùng ê kíp trực tiếp thực hiện các ca phẫu thuật cho khách hàng.",
        feature_4_title: "Bảo Hành Dịch Vụ",
        feature_4_desc: "Chính sách bảo hành rõ ràng, đồng hành cùng khách hàng trọn đời sau phẫu thuật.",
        dr_position: "Giám Đốc Chuyên Môn - Chuyên Gia Phẫu Thuật Tạo Hình",
        ba_tag: "MINH CHỨNG THỰC TẾ",
        ba_title: "Kiến Tạo Nhan Sắc - Trước & Sau Điều Trị",
        ba_desc: "Chất lượng được khẳng định bởi sự thay đổi rõ rệt và sự hài lòng tuyệt đối của hàng ngàn khách hàng dưới bàn tay tài hoa của Dr. Tùng Dương.",
        ba_compare_badge: "Phản hồi thực tế",
        ba_compare_title: "Đánh giá từ khách hàng",
        ba_compare_desc: "Những tin nhắn trò chuyện chân thực từ khách hàng chia sẻ sự hài lòng sau khi phẫu thuật và chăm sóc hậu phẫu tại viện.",
        before: "TRƯỚC",
        after: "SAU PHẪU THUẬT",
        before_after_label: "TRƯỚC & SAU",
        case_1_title: "Căng da mặt Deep Plane Facelift",
        case_1_desc: "Xóa rãnh cười sâu và nâng cơ mặt chảy xệ trẻ hóa toàn diện.",
        case_2_title: "Trẻ hóa khuôn mặt Deep Plane",
        case_2_desc: "Trẻ hóa gương mặt, nâng cơ xóa nếp nhăn chảy xệ.",
        case_3_title: "Căng da trán & Treo cung mày",
        case_3_desc: "Xóa nhăn vùng trán, nâng cung mày tự nhiên trẻ hóa.",
        case_4_title: "Tạo hình mí mắt Plasma",
        case_4_desc: "Tạo nếp mí sắc nét, loại bỏ sụp mí da chùng bẩm sinh.",
        services_tag: "DANH MỤC DỊCH VỤ",
        services_title: "Dịch Vụ Phẫu Thuật Thẩm Mỹ Toàn Diện",
        services_desc: "Chúng tôi cung cấp các giải pháp tạo hình khuôn mặt, nâng cấp vòng một và tạo hình cơ thể ứng dụng công nghệ plasma hiện đại bậc nhất.",
        s1_title: "Phẫu Thuật Trẻ Hóa Khuôn Mặt",
        s1_desc: "Bao gồm căng da mặt tầng sâu (Deep plane facelift), căng da cổ, cấy mỡ tự thân giúp xóa mờ dấu vết thời gian trên gương mặt.",
        s1_bullet_1: "Căng da mặt Deep Plane Facelift",
        s1_bullet_2: "Căng cơ cổ thon gọn",
        s1_bullet_3: "Cấy mỡ Nano Fat rãnh cười",
        view_price_link: "XEM BẢNG GIÁ DỊCH VỤ",
        s2_title: "Thẩm Mỹ Mắt & Mũi",
        s2_desc: "Tạo hình mắt hai mí bồ câu, sửa mí hỏng, tạo hình mũi cấu trúc nâng cao đầu mũi bay thanh thoát chuẩn tỉ lệ.",
        s2_bullet_1: "Cắt mí plasma sắc nét tự nhiên",
        s2_bullet_2: "Nâng mũi bán cấu trúc / cấu trúc",
        s2_bullet_3: "Chỉnh hình dáng mũi cấu trúc sụn tai",
        s3_title: "Phẫu Thuật Thẩm Mỹ Ngực",
        s3_desc: "Nâng ngực nội soi Plasma hạn chế xâm lấn tối đa với túi độn Nano Motiva, Mentor cao cấp chính hãng.",
        s3_bullet_1: "Nâng ngực Plasma sẹo tối thiểu",
        s3_bullet_2: "Treo ngực sa trễ mọi cấp độ",
        s3_bullet_3: "Thu nhỏ núm vú / quầng vú",
        s4_title: "Tạo Hình Cơ Thể - Hút Mỡ",
        s4_desc: "Giảm mỡ thon gọn toàn thân bằng công nghệ hút mỡ hiện đại, hạn chế sưng đau, hồi phục nhanh chóng.",
        s4_bullet_1: "Hút mỡ bụng trên dưới và eo bụng hông",
        s4_bullet_2: "Hút mỡ bắp tay / đùi săn chắc",
        s4_bullet_3: "Tạo hình thành bụng Tummy Tuck",
        s5_title: "Điêu Khắc Không Phẫu Thuật",
        s5_desc: "Sử dụng chất làm đầy (Filler) chính hãng Korea/USA, xóa nếp nhăn nhanh chóng, không tốn thời gian nghỉ dưỡng.",
        s5_bullet_1: "Tiêm filler tạo hình cằm, môi bay",
        s5_bullet_2: "Tiêm Botox xóa nhăn vùng trán, đuôi mắt",
        s5_bullet_3: "Cấy collagen trẻ hóa sáng bóng da",
        s6_title: "Chăm Sóc & Hậu Phẫu Y Khoa",
        s6_desc: "Chăm sóc chuẩn y khoa trọn gói sau phẫu thuật, rửa vết thương, cắt chỉ và chiếu đèn giảm sưng sẹo.",
        s6_bullet_1: "Rửa vết thương & thay băng hàng ngày",
        s6_bullet_2: "Chiếu tia giảm sưng sinh học",
        s6_bullet_3: "Tái khám định kỳ trực tiếp với bác sĩ",
        s6_link: "TƯ VẤN QUY TRÌNH HẬU PHẪU",
        price_tag: "MINH BẠCH - UY TÍN",
        price_title: "Bảng Giá Dịch Vụ Phẫu Thuật Thẩm Mỹ",
        price_desc: "Dr. Tùng Dương mang đến giá trị dịch vụ cao cấp, trọn gói, tuyệt đối không phát sinh chi phí trong suốt quá trình điều trị.",
        filter_all: "Tất Cả Dịch Vụ",
        filter_facial: "Phẫu Thuật Khuôn Mặt (Facial)",
        filter_body: "Tạo Hình & Nâng Ngực (Body)",
        table_col_name: "Tên dịch vụ thẩm mỹ (Kèm phương pháp/vật liệu)",
        table_col_price: "Chi phí (USD)",
        price_note: "* Lưu ý: Giá trên đã bao gồm chi phí phòng mổ vô trùng, xét nghiệm tổng quát, gây tê/gây mê an toàn, thuốc men sau mổ và dịch vụ rửa vết thương thay băng trọn gói. Không phát sinh bất kỳ khoản phụ thu nào.",
        book_now_label: "ĐẶT LỊCH NGAY",
        form_panel_title: "Kiến Tạo Diện Mạo Mới Hôm Hôm Nay",
        form_panel_desc: "Hãy để lại thông tin của bạn. Trợ lý y khoa của Dr. Tùng Dương sẽ liên hệ tư vấn sơ bộ và sắp xếp lịch hẹn ưu tiên phù hợp nhất với quỹ thời gian của bạn.",
        wa_intl_title: "Hỗ trợ quốc tế qua WhatsApp",
        branches_address: "Hà Nội: 123 Phố Huế, Hai Bà Trưng, Hà Nội<br>TP.HCM: 456 Nguyễn Đình Chiểu, Quận 3",
        office_hours: "Làm việc: 08:00 AM - 20:00 PM (Cả CN & ngày lễ)",
        dr_footer_p1: "Đặt lịch trước để tránh chờ đợi",
        dr_footer_p2: "Hotline luôn sẵn sàng",
        form_title: "Thông Tin Đăng Ký Tư Vấn",
        form_lbl_name: "Họ và tên *",
        form_lbl_phone: "Số điện thoại (Zalo) *",
        form_lbl_service: "Chọn dịch vụ quan tâm",
        form_opt_default: "-- Chọn dịch vụ --",
        form_opt_1: "Phẫu thuật trẻ hóa khuôn mặt",
        form_opt_2: "Phẫu thuật tạo hình mắt & mí",
        form_opt_3: "Phẫu thuật thẩm mỹ mũi",
        form_opt_4: "Phẫu thuật nâng ngực Plasma",
        form_opt_5: "Hút mỡ & tạo hình thành bụng",
        form_opt_6: "Thẩm mỹ không phẫu thuật",
        form_lbl_date: "Ngày muốn tư vấn mong muốn",
        form_lbl_msg: "Nhu cầu hoặc câu hỏi chi tiết dành cho Bác sĩ",
        btn_submit: "GỬI YÊU CẦU ĐĂNG KÝ",
        faq_tag: "HỖ TRỢ KHÁCH HÀNG",
        faq_title: "Giải Đáp Thắc Mắc Thường Gặp",
        faq_q1: "1. Phẫu thuật căng da mặt Deep Plane duy trì được bao lâu?",
        faq_a1: "Phương pháp Căng da mặt Deep Plane tác động trực tiếp vào lớp SMAS cơ sâu bên dưới chứ không chỉ kéo căng da bề mặt. Do đó, hiệu quả trẻ hóa có thể duy trì kéo dài từ 20 - 25 năm tùy cơ địa và cách chăm sóc bảo vệ da sau mổ của mỗi khách hàng.",
        faq_q2: "2. Hút mỡ bụng và đùi có gây đau nhiều không và bao lâu đi lại được?",
        faq_a2: "Với công nghệ hút mỡ plasma và kỹ thuật gây tê/mê thế hệ mới, khách hàng chỉ có cảm giác ê ẩm nhẹ như vừa tập thể thao cường độ cao. Thông thường sau 24h khách hàng đã có thể tự đi lại nhẹ nhàng và ra viện hoạt động văn phòng sau 3 - 5 ngày đeo đai định hình bụng/đùi.",
        faq_q3: "3. Viện Thẩm Mỹ có chính sách bảo hành túi độn ngực không?",
        faq_a3: "Có. 100% túi nâng ngực được sử dụng tại viện thẩm mỹ của chúng tôi (Motiva, Mentor) đều là dòng túi chất lượng cao nhất, có mã thẻ bảo hành điện tử chính hãng toàn cầu trọn đời đối với trường hợp bao xơ, nứt vỡ túi độn theo cam kết từ nhà sản xuất.",
        footer_intro: "Chuyên khoa Phẫu thuật Thẩm mỹ chuẩn Y khoa Quốc tế. Kiến tạo đường nét tự nhiên, sang trọng và chuẩn tỷ lệ vàng khuôn diện cho hàng ngàn phụ nữ Á Đông.",
        footer_col_1: "DỊCH VỤ CHÍNH",
        footer_col_2: "HỖ TRỢ",
        footer_col_3: "THÔNG TIN LIÊN HỆ",
        footer_policy_1: "Chính sách bảo mật",
        footer_policy_2: "Điều khoản sử dụng",
        wa_floating_text: "WhatsApp Tư Vấn",
        gallery_tag: "HÌNH ẢNH LÂM SÀNG",
        gallery_title: "Hình Ảnh Phẫu Thuật Thực Tế",
        gallery_desc: "Cận cảnh các ca phẫu thuật lâm sàng chuẩn y khoa được thực hiện trực tiếp bởi Dr. Tùng Dương và ê kíp chuyên nghiệp tại phòng mổ vô trùng đạt chuẩn quốc tế.",
        gallery_zoom: "Xem chi tiết",
        gallery_case1_title: "Quy trình phẫu thuật vô trùng tuyệt đối",
        gallery_case1_desc: "Phòng mổ hiện đại chuẩn y khoa quốc tế khép kín, hạn chế tối đa nguy cơ nhiễm trùng chéo.",
        gallery_case2_title: "Trang thiết bị y tế công nghệ cao",
        gallery_case2_desc: "Ứng dụng dao mổ Plasma thế hệ mới hỗ trợ giảm thiểu chảy máu và rút ngắn thời gian sưng nề.",
        gallery_case3_title: "Bác sĩ trực tiếp thiết kế tỷ lệ vàng",
        gallery_case3_desc: "Dr. Tùng Dương trực tiếp thăm khám, đo vẽ tỉ mỉ nhằm đem lại kết quả cân đối, tự nhiên nhất.",
        gallery_case4_title: "Thực hiện chuẩn xác từng đường may thẩm mỹ",
        gallery_case4_desc: "Kỹ thuật khâu giấu sẹo siêu mảnh giúp hạn chế tối đa dấu vết hậu phẫu sau khi lành thương.",
        gallery_case5_title: "Vật liệu y khoa nhập khẩu chính hãng",
        gallery_case5_desc: "Sử dụng sụn nhân tạo, chỉ thẩm mỹ và các vật liệu cấy ghép có chứng nhận chất lượng FDA.",
        gallery_case6_title: "Chăm sóc chu đáo sau phẫu thuật",
        gallery_case6_desc: "Chế độ hậu phẫu chuyên nghiệp 24/7 giúp kiểm soát quá trình hồi phục nhanh nhất."
    },
    en: {
        nav_home: "Home",
        nav_about: "About Us",
        nav_services: "Services",
        nav_before_after: "Cases",
        nav_price: "Price List",
        nav_faq: "FAQ",
        nav_contact: "Contact",
        book_now: "BOOK APPOINTMENT",
        hero_badge: "International Medical Standard Aesthetic Academy",
        hero_title: "Shaping <span class='text-transparent bg-clip-text bg-gradient-to-r from-brand-gold to-amber-600 text-glow-gold'>Perfect Beauty</span> <br class='hidden sm:inline'> With Modern Technology",
        hero_desc: "Harmonious and luxurious lines crafted by the hands of master plastic surgeon <strong class='text-brand-gold font-bold'>Dr. Tung Duong</strong>. Committed to safety, achieving personalized gold-ratio proportions.",
        stats_med: "Medical Standard",
        stats_happy: "Happy Clients",
        stats_exp: "Years of Practice",
        btn_price: "View Detailed Pricing",
        btn_whatsapp: "WhatsApp Us Now",
        dr_title: "PLASTIC SURGEON",
        dr_quote: "“Creating flawless beauty with dedication, ethics, and surgical precision.”",
        badge_cert_title: "Quality Approved",
        badge_cert_desc: "Ministry of Health Certified",
        stat_1: "Completed Surgeries",
        stat_2: "Excellent Feedback Rating",
        stat_3: "Years of Dedicated Experience",
        stat_4: "24/7 Professional Aftercare",
        about_badge_top: "High-End Quality",
        about_badge_bottom: "Golden ratio for Asian facial structures",
        about_tag: "ABOUT US",
        about_title: "Treatment Built On Dedication,<br>Medical Ethics & Human Values",
        about_desc: "At our aesthetic clinic, every procedure is more than a medical treatment—it is an exquisite piece of living sculpture. <strong>Dr. Tung Duong</strong> ensures natural harmony tailored specifically to your unique anatomy, strictly avoiding standard template looks.",
        feature_1_title: "Premium Materials",
        feature_1_desc: "Uses premium implant materials that are authentically imported and FDA-certified for safety.",
        feature_2_title: "Sterile Environment",
        feature_2_desc: "Surgical theatres strictly conform to high international hygiene and safety regulations.",
        feature_3_title: "The Doctor and the Medical Team",
        feature_3_desc: "The doctor and medical team perform the surgery directly on the client.",
        feature_4_title: "Lifetime Warranty",
        feature_4_desc: "Clear warranty guidelines that support you throughout your recovery.",
        dr_position: "Medical Director - Advanced Plastic Reconstruction Surgeon",
        ba_tag: "REAL EVIDENCE",
        ba_title: "Transformative Results - Before & After",
        ba_desc: "Unmatched quality confirmed by physical transformations and absolute client satisfaction under Dr. Tung Duong's expertise.",
        ba_compare_badge: "Real Feedback",
        ba_compare_title: "Customer Reviews",
        ba_compare_desc: "Genuine chat messages from our patients sharing their satisfaction after surgery and postoperative care.",
        before: "BEFORE",
        after: "AFTER SURGERY",
        before_after_label: "BEFORE & AFTER",
        case_1_title: "Deep Plane Facelift",
        case_1_desc: "Smoothing prominent smile lines and elevating sagging tissue for ultimate facial rejuvenation.",
        case_2_title: "Deep Plane Facial Rejuvenation",
        case_2_desc: "Rejuvenating the face, lifting sagging tissues and smoothing wrinkles.",
        case_3_title: "Forehead Lift & Eyebrow Lift",
        case_3_desc: "Smoothing forehead wrinkles and lifting eyebrows naturally.",
        case_4_title: "Plasma Blepharoplasty",
        case_4_desc: "Creating sharp eyelid folds and correcting congenital sagging skin.",
        services_tag: "SERVICE CATEGORIES",
        services_title: "Comprehensive Aesthetic Solutions",
        services_desc: "Offering tailored solutions for facial rejuvenation, breast enhancement, and body contouring using advanced plasma technologies.",
        s1_title: "Facial Rejuvenation",
        s1_desc: "Includes Deep Plane facelift, neck lift, and fat transfer to smooth signs of aging.",
        s1_bullet_1: "Deep Plane Facelift Rejuvenation",
        s1_bullet_2: "Elegant Neck Lifting",
        s1_bullet_3: "Nano Fat Smile Line Correction",
        view_price_link: "VIEW PRICING MATRIX",
        s2_title: "Eye & Nose Artistry",
        s2_desc: "Providing precise double-eyelid correction, revision work, and tailored structural nose enhancements.",
        s2_bullet_1: "Plasma Eyelid Re-sculpting",
        s2_bullet_2: "Structural & Semi-Structural Rhinoplasty",
        s2_bullet_3: "Ear Cartilage Structural Correction",
        s3_title: "Breast Procedures",
        s3_desc: "Minimally invasive Plasma breast augmentation using premium certified Motiva and Mentor implants.",
        s3_bullet_1: "Plasma Minimally Invasive Augmentation",
        s3_bullet_2: "All Grade Ptosis Corrections (Lift)",
        s3_bullet_3: "Symmetrical Areola & Nipple Resizing",
        s4_title: "Body Contouring & Liposuction",
        s4_desc: "Advanced liposuction solutions designed to reduce body fat gently with rapid downtime.",
        s4_bullet_1: "Full Abdomen & Flank Fat Reduction",
        s4_bullet_2: "Toned Arms & Thigh Reshaping",
        s4_bullet_3: "Complete Tummy Tuck (Abdominoplasty)",
        s5_title: "Non-Surgical Fillers",
        s5_desc: "Utilizing original FDA-approved fillers and Botox to erase wrinkles without any needed downtime.",
        s5_bullet_1: "Charming Lip & Chin Sculpting",
        s5_bullet_2: "Botox Forehead & Eye Wrinkle Smoothing",
        s5_bullet_3: "Collagen Skin Revitalizing Injection",
        s6_title: "Medical Aftercare",
        s6_desc: "Comprehensive y-standard recovery care, wound sanitation, stitch removal, and swelling control therapy.",
        s6_bullet_1: "Daily Sanitization & Dressing",
        s6_bullet_2: "Bio-light Healing Acceleration Therapy",
        s6_bullet_3: "Regular Progress Monitoring by Dr. Duong",
        s6_link: "LEARN AFTERCARE PROCEDURES",
        price_tag: "TRANSPARENCY & INTEGRITY",
        price_title: "Plastic Surgery Fee Schedule",
        price_desc: "Dr. Tung Duong ensures fully clear, inclusive price lists with absolute zero hidden additions during treatment.",
        filter_all: "All Procedures",
        filter_facial: "Facial Procedures",
        filter_body: "Body Procedures",
        table_col_name: "Aesthetic Procedure (Method / Material Detail)",
        table_col_price: "Cost (USD)",
        price_note: "* Note: Listed fees are fully inclusive of state-of-the-art sterile operating room usage, pre-op health tests, safe anesthesia, post-op medications, and follow-up clinical dressing care. No additional fees.",
        book_now_label: "SECURE YOUR SLOT",
        form_panel_title: "Embrace Your New Elegance Today",
        form_panel_desc: "Provide your details. Our clinical care assistants will call you to provide initial guidance and reserve an appointment at your earliest convenience.",
        wa_intl_title: "Worldwide WhatsApp Support",
        branches_address: "Hanoi: 123 Hue Street, Hai Ba Trung District, Hanoi<br>HCMC: 456 Nguyen Dinh Chieu, District 3, HCMC",
        office_hours: "Hours: 08:00 AM - 20:00 PM (Including Sundays & Holidays)",
        dr_footer_p1: "Pre-book to bypass general waiting queues",
        dr_footer_p2: "Emergency Hotlines Active",
        form_title: "Appointment Request Form",
        form_lbl_name: "Full Name *",
        form_lbl_phone: "Phone / WhatsApp *",
        form_lbl_service: "Procedure of Interest",
        form_opt_default: "-- Select Service --",
        form_opt_1: "Facial Rejuvenation",
        form_opt_2: "Eye & Eyelid Sculpting",
        form_opt_3: "Nose Sculpting",
        form_opt_4: "Plasma Breast Augmentation",
        form_opt_5: "Lipo & Tummy Tuck",
        form_opt_6: "Non-Surgical Beautification",
        form_lbl_date: "Preferred Consult Date",
        form_lbl_msg: "Individual Requests or Questions for Dr. Duong",
        btn_submit: "SEND RESERVATION REQUEST",
        faq_tag: "CUSTOMER SUPPORT",
        faq_title: "Frequently Answered Questions",
        faq_q1: "1. How long does a Deep Plane Facelift rejuvenate the face?",
        faq_a1: "The Deep Plane technique works beneath the SMAS layer of tissue instead of merely stretching the top skin layer. Rejuvenation results typically last 20 to 25 years, depending on your lifestyle and skin health.",
        faq_q2: "2. Is liposuction very painful, and how soon can I walk comfortably?",
        faq_a2: "With modern plasma techniques and advanced pain management, clients feel mild soreness similar to an intense workout. Most patients can walk gently within 24 hours and return to office work after 3 to 5 days of wearing compression garments.",
        faq_q3: "3. Is there a certified warranty for breast implants?",
        faq_a3: "Yes. All implants used in our academy (Motiva, Mentor) are premium devices carrying lifetime worldwide digital certificates from manufacturers against rupture or capsular contracture.",
        footer_intro: "Elite International Standard Plastic Surgery. Sculpting natural, elegant contours matching gold-ratio facial shapes for global Asian clients.",
        footer_col_1: "MAIN PROCEDURES",
        footer_col_2: "SUPPORT LINKS",
        footer_col_3: "CONTACT CHANNELS",
        footer_policy_1: "Privacy Guidelines",
        footer_policy_2: "Terms of Use",
        wa_floating_text: "WhatsApp Consult",
        gallery_tag: "CLINICAL GALLERY",
        gallery_title: "Real Surgery Images",
        gallery_desc: "Close-up clinical surgery cases performed directly by Dr. Tùng Dương and our professional medical team in an international sterile operating room.",
        gallery_zoom: "View Details",
        gallery_case1_title: "Absolute sterile surgical environment",
        gallery_case1_desc: "Modern closed international medical standard operating room, minimizing cross-infection risk.",
        gallery_case2_title: "High-tech medical equipment",
        gallery_case2_desc: "Applying next-generation Plasma surgical knives to minimize bleeding and shorten swelling time.",
        gallery_case3_title: "Doctor-designed golden ratio",
        gallery_case3_desc: "Dr. Tùng Dương directly examines and precisely drafts to achieve the most balanced, natural outcome.",
        gallery_case4_title: "Precise aesthetic suturing",
        gallery_case4_desc: "Ultra-fine scarless suturing technique minimizes postoperative marks after healing.",
        gallery_case5_title: "Authentic imported medical materials",
        gallery_case5_desc: "Using FDA-certified implants, surgical threads, and medical prosthetics.",
        gallery_case6_title: "Dedicated postoperative care",
        gallery_case6_desc: "Professional 24/7 aftercare system to monitor and ensure the fastest recovery process."
    },
    zh: {
        nav_home: "首页",
        nav_about: "医生介绍",
        nav_services: "整形项目",
        nav_before_after: "真实案例",
        nav_price: "价格表",
        nav_faq: "常见问题",
        nav_contact: "联系预约",
        book_now: "立即预约",
        hero_badge: "国际医疗标准整形美容医院",
        hero_title: "借助现代医疗技术 <br> 雕刻 <span class='text-transparent bg-clip-text bg-gradient-to-r from-brand-gold to-amber-600 text-glow-gold'>极致黄金比例美</span>",
        hero_desc: "由高级整形美容外科专家 <strong class='text-brand-gold font-bold'>杨松医生 (Dr. Tùng Dương)</strong> 亲自操作。确保百分之百安全，力求打造面部五官黄金和谐曲线。",
        stats_med: "医疗级标准",
        stats_happy: "满意客户",
        stats_exp: "年执业经验",
        btn_price: "查看项目价格表",
        btn_whatsapp: "WhatsApp 立即咨询",
        dr_title: "首席整形外科医生",
        dr_quote: "“用仁心、医术以及至臻艺术态度雕琢每一份美丽。”",
        badge_cert_title: "安全质量",
        badge_cert_desc: "卫生部合法许可证",
        stat_1: "成功开展手术数",
        stat_2: "客户五星极佳反馈",
        stat_3: "多年专业临床经验",
        stat_4: "24/7 术后贴心护理",
        about_badge_top: "高水平美学",
        about_badge_bottom: "定制打造专属于亚洲面庞的黄金比例",
        about_tag: "关于我们",
        about_title: "遵循医德、仁心与<br>人文主义的专属医疗定制服务",
        about_desc: "在我们的整形美容医院，每一次手术不仅是医术的体现，更是打造一件生动的雕塑艺术品。<strong>杨松医生</strong>始终坚持自然和谐的塑美宗旨，绝不千人一面、死板复制。",
        feature_1_title: "进口顶级假体",
        feature_1_desc: "采用经由正规渠道进口且获FDA安全认证的优质植入材料。",
        feature_2_title: "无菌手术室",
        feature_2_desc: "符合国际严苛无菌标准的千级流层手术室，将感染风险降至最低。",
        feature_3_title: "醫生與醫療團隊",
        feature_3_desc: "醫生和醫療團隊直接為客戶進行手術。",
        feature_4_title: "完善质保制度",
        feature_4_desc: "清晰签署的材料和术后质保，让您的蜕美之路免除后顾之忧。",
        dr_position: "医疗院长 - 资深整形外科重建专家",
        ba_tag: "真实对比展示",
        ba_title: "面貌革新 - 术前术后即刻效果",
        ba_desc: "用真实的高清病例，共同见证在杨松医生精耽医术下的奇迹蜕变。",
        ba_compare_badge: "客户真实反馈",
        ba_compare_title: "客户评价分享",
        ba_compare_desc: "来自求美者真实的聊天记录，分享她们在接受手术及术后康复护理后的满意心得。",
        before: "术前",
        after: "术后即刻",
        before_after_label: "术前 & 术后",
        case_1_title: "深层SMAS拉皮除皱术",
        case_1_desc: "直击深层软组织下垂，抚平法令纹，重塑紧致年轻轮廓。",
        case_2_title: "Deep Plane 面部年轻化",
        case_2_desc: "提升下垂组织，抚平皱纹，重塑年轻轮廓。",
        case_3_title: "额头拉皮与提眉术",
        case_3_desc: "抚平额头皱纹，自然提升眉弓，焕发年轻神采。",
        case_4_title: "Plasma 精细双眼皮",
        case_4_desc: "形成清晰双眼皮线条，矫正先天性眼睑松弛。",
        services_tag: "整形手术分类",
        services_title: "全方位一站式医疗塑形解决方案",
        services_desc: "结合先进的面部抗衰、丰胸、吸脂和非手术注射美容，全方位为您雕琢无瑕身姿。",
        s1_title: "面部年轻化抗衰",
        s1_desc: "包括深层提拉（Deep Plane拉皮）、颈部除皱和自体脂肪填充，抹去岁月痕迹。",
        s1_bullet_1: "深层SMAS拉皮除皱提拉",
        s1_bullet_2: "下颌缘及颈部皮肤收紧",
        s1_bullet_3: "自体脂肪面部年轻化填充",
        view_price_link: "进入价格表明细",
        s2_title: "眼鼻精细化雕塑",
        s2_desc: "眼部综合整形、隆鼻失败修复、面部美学轮廓重塑。",
        s2_bullet_1: "Plasma精细化韩式美眼术",
        s2_bullet_2: "耳软骨/肋软骨综合性鼻整形",
        s2_bullet_3: "失败鼻整形精准修复设计",
        s3_title: "美胸及乳房整形",
        s3_desc: "使用Motiva和Mentor等高分子医用乳房假体，开展内窥镜微创安全丰胸。",
        s3_bullet_1: "内窥镜微创双平面丰胸术",
        s3_bullet_2: "各类重度乳房下垂矫正术",
        s3_bullet_3: "乳头乳晕精致塑形美化",
        s4_title: "吸脂塑身及身体塑形",
        s4_desc: "微创高效吸脂，温和抽取身体多余脂肪，快速雕刻马甲线、S曲线。",
        s4_bullet_1: "腹部全环吸（上腹、下腹、两侧腰）",
        s4_bullet_2: "手臂及大腿环状精细吸脂",
        s4_bullet_3: "腹壁成形术（解决产后肚皮松弛）",
        s5_title: "微整形注射美容",
        s5_desc: "使用原装正品玻尿酸及除皱针，快速抚平细纹，补充面部容积，无需恢复期。",
        s5_bullet_1: "玻尿酸打造立体下巴与性感唇部",
        s5_bullet_2: "注射除皱（额头纹、鱼尾纹）",
        s5_bullet_3: "胶原蛋白全面部水光亮肤",
        s6_title: "医用术后康复护理",
        s6_desc: "高规格院级换药、拆线、生物红蓝光理疗收敛，有效抗炎、淡化术后疤痕。",
        s6_bullet_1: "医护每日换药清洁与皮肤护理",
        s6_bullet_2: "生物光能消肿止痛加速仪治疗",
        s6_bullet_3: "杨松院长术后定期回访复查",
        s6_link: "查看完整换药和售后流程",
        price_tag: "公开、公平、透明",
        price_title: "整形项目价格公示表",
        price_desc: "杨松医生承诺所有项目价格均实行包干打包制，绝不在诊疗期间随意增加任何隐形消费。",
        filter_all: "所有大类",
        filter_facial: "面部外科手术",
        filter_body: "胸部及体形外科",
        table_col_name: "整形美容细分项目 (选用方案/假体详情)",
        table_col_price: "最终包干价 (美元)",
        price_note: "* 备注：上述费用已包含无菌手术室、全套化验检查、安全麻醉费、术后配药以及拆线前的全部院内理疗，不设置任何其他加收收费。",
        book_now_label: "立即抢占名额",
        form_panel_title: "今天，开启您的优雅华丽蜕变",
        form_panel_desc: "请在右侧提交您的基础联络方式。我们的医务秘书将在15分钟内与您联系，解答疑问并为您锁定杨松医生的优先面诊通道。",
        wa_intl_title: "全球 WhatsApp 专线服务",
        branches_address: "河内分院：河内市二征夫人区裴市春坊顺化街123号<br>胡志明分院：胡志明市第三区阮廷炤路456号",
        office_hours: "执业时间：每日 08:00 AM - 20:00 PM (周六、周日及节假日照常开诊)",
        dr_footer_p1: "提前预约可享直接免排队面诊通道",
        dr_footer_p2: "紧急救助电话随时在线",
        form_title: "整形面诊预约登记表",
        form_lbl_name: "您的姓名 *",
        form_lbl_phone: "电话 / 微信 / WhatsApp *",
        form_lbl_service: "您所关注的医美方向",
        form_opt_default: "-- 请选择医美大类 --",
        form_opt_1: "面部深层除皱抗衰",
        form_opt_2: "双眼皮及眼部整形",
        form_opt_3: "耳软骨/假体综合隆鼻",
        form_opt_4: "假体/自体脂肪美胸",
        form_opt_5: "吸脂塑身与大腿吸脂",
        form_opt_6: "玻尿酸/除皱针注射",
        form_lbl_date: "希望来院面诊的日期",
        form_lbl_msg: "是否有其他手术史或想对医生说的话",
        btn_submit: "确认提交预约资料",
        faq_tag: "客户关怀与咨询",
        faq_title: "解答广大求美者最关心的疑问",
        faq_q1: "1. 深层拉皮手术效果通常可以维持几年？",
        faq_a1: "由于手术触及极深层的SMAS肌肉骨膜层，不仅收紧多余皮肤而且提升内部肌肉架构。因此效果明显，基本可以比同龄人年轻20至25年。",
        faq_q2: "2. 吸脂手术痛不痛？术后需要多久才能正常通勤？",
        faq_a2: "在全身麻醉或镇静麻醉辅助下，手术过程没有任何痛感。术后仅有如高强度撸铁后的肌肉酸胀感。一般术后24小时即可正常漫步走动，3至5天可正常到办公室工作。",
        faq_q3: "3. 假体隆胸术后对假体破裂有终身保修政策吗？",
        faq_a3: "有的。我们只选用通过FDA、CE以及卫健委批准的国际知名假体Motiva和Mentor，厂家提供针对破裂及重度包膜挛缩的终身保换原厂质保保障。",
        footer_intro: "国际一流水准的高端私立整形美容机构。秉持高标准美学态度，用完美的黄金比例为全亚洲精英女性保驾护航。",
        footer_col_1: "核心业务板块",
        footer_col_2: "快速绿色通道",
        footer_col_3: "联系沟通渠道",
        footer_policy_1: "个人隐私保护制度",
        footer_policy_2: "用户服务协议条款",
        wa_floating_text: "WhatsApp 咨询",
        gallery_tag: "临床案例展示",
        gallery_title: "真实手术过程图片",
        gallery_desc: "由杨松医生 (Dr. Tùng Dương) 及其专业医疗团队在符合国际无菌标准手术室中进行的真实临床手术案例近距离展示。",
        gallery_zoom: "查看详情",
        gallery_case1_title: "绝对无菌的手术环境",
        gallery_case1_desc: "现代封闭式国际医疗标准手术室，最大限度减少交叉感染风险。",
        gallery_case2_title: "高科技医疗设备",
        gallery_case2_desc: "应用新一代等离子手术刀，减少出血并缩短术后肿胀时间。",
        gallery_case3_title: "医生亲自设计黄金比例",
        gallery_case3_desc: "杨松医生亲自问诊、精细测量画线，以求打造最自然和谐的效果。",
        gallery_case4_title: "精细缝合不留痕迹",
        gallery_case4_desc: "超细隐形缝合技术，在愈合后最大程度地减少术后疤痕。",
        gallery_case5_title: "正规进口医疗材料",
        gallery_case5_desc: "使用经过美国FDA认证的假体材料、美容线和植入材料。",
        gallery_case6_title: "全天候术后悉心护理",
        gallery_case6_desc: "提供24/7全天候术后跟踪关怀，保障伤口以最快速度恢复。"
    },

    id: {
        nav_home: "Beranda",
        nav_about: "Tentang Kami",
        nav_services: "Layanan",
        nav_before_after: "Sebelum & Sesudah",
        nav_price: "Daftar Harga",
        nav_faq: "FAQ",
        nav_contact: "Hubungi Kami",
        book_now: "BUAT JANJI TEMU",
        hero_badge: "Akademi Estetika Standar Medis Internasional",
        hero_title: "Membentuk <span class='text-transparent bg-clip-text bg-gradient-to-r from-brand-gold to-amber-600 text-glow-gold'>Kecantikan Sempurna</span> <br class='hidden sm:inline'> Dengan Teknologi Modern",
        hero_desc: "Garis wajah dan tubuh yang harmonis serta mewah dirancang langsung oleh spesialis bedah plastik ternama <strong class='text-brand-gold font-bold'>Dr. Tung Duong</strong>. Berkomitmen pada keamanan total untuk mencapai proporsi golden ratio yang dipersonalisasi.",
        stats_med: "Standar Medis",
        stats_happy: "Klien Puas",
        stats_exp: "Tahun Pengalaman",
        btn_price: "Lihat Detail Harga",
        btn_whatsapp: "Konsultasi WhatsApp Sekarang",
        dr_title: "DOKTER BEDAH PLASTIK",
        dr_quote: "“Menciptakan kecantikan tanpa cela dengan dedikasi, etika medis, dan presisi bedah.”",
        badge_cert_title: "Kualitas Terjamin",
        badge_cert_desc: "Sertifikasi Kementerian Kesehatan",
        stat_1: "Operasi yang Berhasil",
        stat_2: "Ulasan Bintang 5 Klien",
        stat_3: "Tahun Praktik Profesional",
        stat_4: "Perawatan Pasca-Operasi 24/7",
        about_badge_top: "Estetika High-End",
        about_badge_bottom: "Golden ratio untuk struktur wajah Asia",
        about_tag: "TENTANG KAMI",
        about_title: "Perawatan Berdasarkan Dedikasi,<br>Etika Medis & Nilai Kemanusiaan",
        about_desc: "Di klinik estetika kami, setiap prosedur lebih dari sekadar perawatan medis—ini adalah karya seni pahat hidup yang indah. <strong>Dr. Tung Duong</strong> memastikan keharmonisan alami yang disesuaikan secara khusus dengan anatomi unik Anda, menghindari hasil yang kaku dan seragam.",
        feature_1_title: "Bahan Premium",
        feature_1_desc: "Menggunakan bahan implan premium asli yang diimpor secara resmi dan bersertifikat FDA demi keamanan.",
        feature_2_title: "Lingkungan Steril",
        feature_2_desc: "Kamar bedah sepenuhnya memenuhi standar sterilisasi dan keamanan tinggi internasional.",
        feature_3_title: "Dokter & Tim Medis",
        feature_3_desc: "Dokter dan tim medis ahli melakukan tindakan operasi secara langsung kepada pasien.",
        feature_4_title: "Garansi Seumur Hidup",
        feature_4_desc: "Kebijakan garansi yang jelas untuk mendukung Anda di sepanjang proses pemulihan.",
        dr_position: "Direktur Medis - Spesialis Bedah Rekonstruksi & Plastik Tingkat Lanjut",
        ba_tag: "BUKTI NYATA",
        ba_title: "Hasil Transformasi - Sebelum & Sesudah",
        ba_desc: "Kualitas tak tertandingi yang dibuktikan oleh perubahan fisik nyata dan kepuasan mutlak klien di bawah keahlian Dr. Tung Duong.",
        ba_compare_badge: "Umpan Balik Nyata",
        ba_compare_title: "Ulasan Pelanggan",
        ba_compare_desc: "Pesan obrolan asli dari pasien kami yang membagikan kepuasan mereka setelah operasi dan perawatan pasca operasi.",
        before: "SEBELUM",
        after: "SETELAH OPERASI",
        before_after_label: "SEBELUM & SESUDAH",
        case_1_title: "Deep Plane Facelift",
        case_1_desc: "Menghaluskan garis senyum yang dalam dan mengencangkan jaringan wajah yang kendur untuk peremajaan maksimal.",
        case_2_title: "Rejuvenasi Wajah Deep Plane",
        case_2_desc: "Meremajakan wajah, mengencangkan jaringan kendur dan menghapus kerutan.",
        case_3_title: "Forehead Lift & Eyebrow Lift",
        case_3_desc: "Menghaluskan kerutan dahi dan mengangkat alis secara alami.",
        case_4_title: "Blefaroplasti Plasma",
        case_4_desc: "Membentuk lipatan kelopak mata yang tajam dan memperbaiki kulit kendur.",
        services_tag: "KATEGORI LAYANAN",
        services_title: "Solusi Estetika Medis Komprehensif",
        services_desc: "Menawarkan solusi khusus untuk peremajaan wajah, augmentasi payudara, dan kontur tubuh menggunakan teknologi plasma canggih.",
        s1_title: "Peremajaan Wajah",
        s1_desc: "Meliputi Deep Plane facelift, neck lift, dan transfer lemak untuk menghapus tanda-tanda penuaan.",
        s1_bullet_1: "Peremajaan Deep Plane Facelift",
        s1_bullet_2: "Pengencangan Leher Anggun",
        s1_bullet_3: "Koreksi Garis Senyum dengan Nano Fat",
        view_price_link: "LIHAT DAFTAR HARGA LENGKAP",
        s2_title: "Estetika Mata & Hidung",
        s2_desc: "Koreksi kelopak mata ganda yang presisi, operasi revisi, dan pembentukan hidung struktural yang dipersonalisasi.",
        s2_bullet_1: "Resculpting Kelopak Mata Plasma",
        s2_bullet_2: "Rhinoplasty Struktural & Semi-Struktural",
        s2_bullet_3: "Koreksi Struktural Tulang Rawan Telinga",
        s3_title: "Prosedur Payudara",
        s3_desc: "Augmentasi payudara Plasma invasif minimal menggunakan implan Motiva dan Mentor premium berlisensi.",
        s3_bullet_1: "Augmentasi Invasif Minimal Plasma",
        s3_bullet_2: "Koreksi Ptosis Semua Tingkat (Lift)",
        s3_bullet_3: "Pengecilan Areola & Puting yang Simetris",
        s4_title: "Kontur Tubuh & Liposuction",
        s4_desc: "Solusi liposuction canggih yang dirancang untuk mengurangi lemak tubuh secara lembut dengan pemulihan cepat.",
        s4_bullet_1: "Pengecilan Lemak Perut & Pinggul",
        s4_bullet_2: "Pembentukan Lengan & Paha Kencang",
        s4_bullet_3: "Tummy Tuck Lengkap (Abdominoplasti)",
        s5_title: "Filler Non-Bedah",
        s5_desc: "Menggunakan filler orisinal bersertifikat FDA dan Botox untuk menghapus kerutan tanpa waktu pemulihan.",
        s5_bullet_1: "Pembentukan Bibir & Dagu yang Menawan",
        s5_bullet_2: "Botox Kerutan Dahi & Sudut Mata",
        s5_bullet_3: "Injeksi Kolagen Revitalisasi Kulit Glowing",
        s6_title: "Perawatan Pasca-Operasi Medis",
        s6_desc: "Perawatan pemulihan pasca-operasi komprehensif, pembersihan luka, pelepasan jahitan, dan terapi bio-light pengurang bengkak.",
        s6_bullet_1: "Pembersihan Luka & Perban Harian",
        s6_bullet_2: "Terapi Cahaya Biologis Mempercepat Penyembuhan",
        s6_bullet_3: "Pemantauan Berkala Langsung oleh Dr. Duong",
        s6_link: "PELAJARI PROSEDUR PASCA-OPERASI",
        price_tag: "TRANSPARENSI & INTEGRITAS",
        price_title: "Daftar Tarif Bedah Plastik",
        price_desc: "Dr. Tung Duong menjamin daftar harga yang jelas, paket lengkap, tanpa ada biaya tersembunyi selama masa perawatan.",
        filter_all: "Semua Prosedur",
        filter_facial: "Prosedur Wajah",
        filter_body: "Prosedur Tubuh",
        table_col_name: "Prosedur Estetika (Metode / Detail Bahan)",
        table_col_price: "Biaya (USD)",
        price_note: "* Catatan: Biaya yang tertera sudah termasuk penggunaan kamar bedah steril modern, tes kesehatan pra-operasi, anestesi yang aman, obat pasca-operasi, dan perawatan penggantian perban klinis. Tidak ada biaya tambahan.",
        book_now_label: "AMANKAN SLOT ANDA",
        form_panel_title: "Wujudkan Penampilan Baru Anda Hari Ini",
        form_panel_desc: "Silakan isi detail Anda. Asisten medis kami akan segera menghubungi Anda dalam waktu 15 menit untuk memberikan panduan awal dan memesan jadwal prioritas.",
        wa_intl_title: "Layanan WhatsApp Internasional",
        branches_address: "Halan Hue 123, Distrik Hai Ba Trung, Hanoi<br>HCMC: Jalan Nguyen Dinh Chieu 456, Distrik 3, HCMC",
        office_hours: "Jam Kerja: 08:00 AM - 20:00 PM (Buka setiap hari termasuk hari Minggu & Libur Nasional)",
        dr_footer_p1: "Daftar terlebih dahulu untuk menghindari antrean panjang",
        dr_footer_p2: "Hotline Darurat Aktif 24 Jam",
        form_title: "Formulir Pendaftaran Janji Temu",
        form_lbl_name: "Nama Lengkap Anda *",
        form_lbl_phone: "Nomor Telepon / WhatsApp *",
        form_lbl_service: "Prosedur yang Diminati",
        form_opt_default: "-- Pilih Layanan --",
        form_opt_1: "Peremajaan Kulit Wajah",
        form_opt_2: "Bedah Kelopak Mata & Area Mata",
        form_opt_3: "Bedah Rhinoplasty (Hidung)",
        form_opt_4: "Augmentasi Payudara Plasma",
        form_opt_5: "Liposuction & Tummy Tuck",
        form_opt_6: "Kecantikan Non-Bedah",
        form_lbl_date: "Tanggal Konsultasi yang Diinginkan",
        form_lbl_msg: "Kebutuhan atau Pertanyaan Detail untuk Dokter",
        btn_submit: "KIRIM PERMINTAAN RESERVASI",
        faq_tag: "LAYANAN & PERTANYAAN PELANGGAN",
        faq_title: "Menjawab Pertanyaan yang Sering Diajukan",
        faq_q1: "1. Berapa lama hasil Deep Plane Facelift dapat bertahan?",
        faq_a1: "Teknik Deep Plane bekerja langsung di bawah lapisan otot SMAS terdalam, tidak hanya sekadar meregangkan kulit luar. Oleh karena itu, hasil peremajaan wajah dapat bertahan sangat lama, berkisar antara 20 hingga 25 tahun tergantung kondisi kulit dan gaya hidup Anda.",
        faq_q2: "2. Apakah liposuction sangat menyakitkan, dan seberapa cepat saya bisa berjalan normal?",
        faq_a2: "Di bawah bantuan anestesi modern, prosedur ini sepenuhnya bebas rasa sakit. Setelah operasi, klien hanya merasakan pegal ringan seperti setelah olahraga berat. Umumnya, dalam 24 jam pasien sudah bisa berjalan perlahan, dan dapat kembali bekerja kantoran dalam 3-5 hari setelah mengenakan korset kompresi khusus.",
        faq_q3: "3. Apakah ada garansi seumur hidup untuk implan payudara?",
        faq_a3: "Ya. Semua implan payudara yang digunakan di akademi kami (Motiva, Mentor) adalah perangkat bersertifikat premium yang memiliki kartu garansi digital resmi pabrik secara global seumur hidup terhadap kasus kebocoran implan atau kontraktur kapsul.",
        footer_intro: "Klinik Spesialis Bedah Plastik Estetika Standar Internasional Premium. Memahat kontur tubuh alami dan mewah yang sesuai dengan proporsi golden ratio wajah Asia.",
        footer_col_1: "PROSEDUR UTAMA",
        footer_col_2: "AKSES CEPAT",
        footer_col_3: "SALURAN HUBUNGAN",
        footer_policy_1: "Kebijakan Privasi",
        footer_policy_2: "Ketentuan Penggunaan",
        wa_floating_text: "Konsultasi WhatsApp",
        gallery_tag: "GALERI KLINIS",
        gallery_title: "Foto Bedah Realistis",
        gallery_desc: "Foto jarak dekat dari kasus bedah klinis yang dilakukan langsung oleh Dr. Tùng Dương dan tim medis profesional di ruang operasi steril berstandar internasional.",
        gallery_zoom: "Lihat Detail",
        gallery_case1_title: "Lingkungan operasi steril mutlak",
        gallery_case1_desc: "Ruang operasi standar medis internasional tertutup modern, meminimalkan risiko infeksi silang.",
        gallery_case2_title: "Peralatan medis teknologi tinggi",
        gallery_case2_desc: "Menggunakan pisau bedah Plasma generasi terbaru untuk mengurangi pendarahan dan mempercepat pemulihan bengkak.",
        gallery_case3_title: "Rasio emas dirancang langsung oleh dokter",
        gallery_case3_desc: "Dr. Tùng Dương memeriksa langsung dan menggambar dengan teliti demi hasil paling seimbang dan alami.",
        gallery_case4_title: "Jahitan estetika presisi tinggi",
        gallery_case4_desc: "Teknik jahitan halus tersembunyi meminimalkan bekas luka pasca operasi setelah sembuh.",
        gallery_case5_title: "Bahan medis impor resmi",
        gallery_case5_desc: "Menggunakan implan, benang bedah, dan bahan bersertifikasi FDA resmi.",
        gallery_case6_title: "Perawatan pasca operasi profesional",
        gallery_case6_desc: "Sistem perawatan pasca bedah 24/7 untuk memastikan pemulihan yang cepat dan aman."
    },
    th: {
        nav_home: "หน้าแรก",
        nav_about: "เกี่ยวกับเรา",
        nav_services: "บริการของเรา",
        nav_before_after: "รีวิวลูกค้า",
        nav_price: "ตารางราคา",
        nav_faq: "คำถามที่พบบ่อย",
        nav_contact: "ติดต่อเรา",
        book_now: "นัดหมายล่วงหน้า",
        hero_badge: "สถาบันศัลยกรรมความงามมาตรฐานการแพทย์สากล",
        hero_title: "รังสรรค์ <span class='text-transparent bg-clip-text bg-gradient-to-r from-brand-gold to-amber-600 text-glow-gold'>ความงามที่สมบูรณ์แบบ</span> <br class='hidden sm:inline'> ด้วยเทคโนโลยีทันสมัย",
        hero_desc: "ปรับโครงหน้าและทรวดทรงให้งดงามหรูหราอย่างเป็นธรรมชาติ โดยศัลยแพทย์ผู้เชี่ยวชาญระดับสูง <strong class='text-brand-gold font-bold'>นพ. ตุง เซือง (Dr. Tung Duong)</strong> มั่นใจในความปลอดภัยสูงสุดตามสัดส่วนทองคำของคุณ",
        stats_med: "มาตรฐานการแพทย์",
        stats_happy: "ลูกค้าพึงพอใจ",
        stats_exp: "ปีแห่งประสบการณ์",
        btn_price: "ดูรายละเอียดราคา",
        btn_whatsapp: "ปรึกษาผ่าน WhatsApp ทันที",
        dr_title: "ศัลยแพทย์ตกแต่ง",
        dr_quote: "“สร้างสรรค์ความงามอย่างไร้ที่ติ ด้วยความใส่ใจ จรรยาบรรณ และความแม่นยำทางศัลยกรรม”",
        badge_cert_title: "รับรองคุณภาพ",
        badge_cert_desc: "ผ่านการรับรองจากกระทรวงสาธารณสุข",
        stat_1: "การผ่าตัดที่สำเร็จ",
        stat_2: "คะแนนรีวิวดีเยี่ยม",
        stat_3: "ปีแห่งการดูแลด้วยใจ",
        stat_4: "ดูแลหลังผ่าตัด 24/7",
        about_badge_top: "ความงามระดับไฮเอนด์",
        about_badge_bottom: "สัดส่วนทองคำสำหรับโครงหน้าเอเชีย",
        about_tag: "เกี่ยวกับเรา",
        about_title: "การรักษาที่เปี่ยมด้วยความใส่ใจ<br>จริยธรรมทางการแพทย์และคุณค่าแห่งความเป็นมนุษย์",
        about_desc: "ที่คลินิกศัลยกรรมตกแต่งของเรา ทุกหัตถการเป็นมากกว่าการรักษาทางการแพทย์ แต่คืองานประติมากรรมที่มีชีวิตอันประณีต <strong>นพ. ตุง เซือง (Dr. Tung Duong)</strong> รังสรรค์ความงามที่กลมกลืนเป็นธรรมชาติเฉพาะบุคคล หลีกเลี่ยงผลลัพธ์ที่ซ้ำซากจำเจ",
        feature_1_title: "วัสดุเกรดพรีเมียม",
        feature_1_desc: "เลือกใช้วัสดุฝังในพรีเมียมของแท้ที่ผ่านการรับรองจาก FDA เพื่อความปลอดภัยสูงสุด",
        feature_2_title: "ห้องผ่าตัดปลอดเชื้อ",
        feature_2_desc: "ห้องผ่าตัดได้มาตรฐานปลอดเชื้อระดับสากล ปลอดภัย ไร้กังวลเรื่องการติดเชื้อ",
        feature_3_title: "แพทย์และทีมแพทย์ผู้เชี่ยวชาญ",
        feature_3_desc: "แพทย์และทีมแพทย์ผู้เชี่ยวชาญดำเนินการผ่าตัดให้แก่ลูกค้าโดยตรง",
        feature_4_title: "การรับประกันตลอดชีพ",
        feature_4_desc: "เงื่อนไขการรับประกันที่ชัดเจน พร้อมเคียงข้างคุณตลอดเส้นทางการพักฟื้น",
        dr_position: "ผู้อำนวยการแพทย์ - ผู้เชี่ยวชาญด้านศัลยกรรมตกแต่งและเสริมสร้างขั้นสูง",
        ba_tag: "ผลลัพธ์จริง",
        ba_title: "ความเปลี่ยนแปลงที่พิสูจน์ได้ - ก่อนและหลัง",
        ba_desc: "คุณภาพที่ยืนยันได้ด้วยผลลัพธ์การเปลี่ยนแปลงจริงและความพึงพอใจสูงสุดของลูกค้า ภายใต้การดูแลของ นพ. ตุง เซือง",
        ba_compare_badge: "ผลตอบรับจริง",
        ba_compare_title: "รีวิวจากลูกค้า",
        ba_compare_desc: "ข้อความแชทจริงจากคนไข้ที่แบ่งปันความพึงพอใจหลังการผ่าตัดและการดูแลหลังผ่าตัดของเรา",
        before: "ก่อนทำ",
        after: "หลังทำทันที",
        before_after_label: "ก่อน & หลังทำ",
        case_1_title: "ดึงหน้าส่วนลึก (Deep Plane Facelift)",
        case_1_desc: "แก้ปัญหาร่องแก้มลึกและยกกระชับผิวที่หย่อนคล้อยเพื่อความอ่อนเยาว์อย่างเป็นธรรมชาติ",
        case_2_title: "ดึงหน้าย้อนวัยเทคนิค Deep Plane",
        case_2_desc: "ดึงกระชับใบหน้า ลดความหย่อนคล้อยและริ้วรอยแห่งวัย",
        case_3_title: "ดึงหน้าผาก & ดึงหางตา",
        case_3_desc: "ลดเลือนริ้วรอยบริเวณหน้าผากและยกคิ้วอย่างเป็นธรรมชาติ",
        case_4_title: "ศัลยกรรมตาสองชั้นพลาสม่า",
        case_4_desc: "สร้างชั้นตาที่คมชัดและแก้ไขภาวะหนังตาตกหย่อนคล้อย",
        services_tag: "ประเภทบริการ",
        services_title: "บริการศัลยกรรมความงามครบวงจร",
        services_desc: "มอบทางเลือกที่ออกแบบเฉพาะสำหรับการฟื้นฟูผิวหน้า การเสริมหน้าอก และการดูดไขมันกระชับสัดส่วนด้วยเทคโนโลยีพลาสม่าที่ล้ำสมัย",
        s1_title: "การฟื้นฟูผิวหน้า",
        s1_desc: "บริการดึงหน้าส่วนลึก (Deep Plane Facelift) ดึงคอ และเติมไขมันหน้าเด็กเพื่อลบเลือนริ้วรอยแห่งวัย",
        s1_bullet_1: "ดึงหน้าเทคนิค Deep Plane",
        s1_bullet_2: "ดึงคอยกกระชับ",
        s1_bullet_3: "เติมไขมันสเต็มเซลล์ร่องแก้ม",
        view_price_link: "ดูตารางราคาบริการทั้งหมด",
        s2_title: "ศัลยกรรมตาและจมูก",
        s2_desc: "แก้ไขตาสองชั้น ปรับแต่งจมูกโครงสร้าง และแก้ไขงานจมูกที่เคยพังให้กลับมาสวยงาม",
        s2_bullet_1: "ทำตาสองชั้นพลาสม่าเรียบเนียน",
        s2_bullet_2: "เสริมจมูกกึ่งโครงสร้าง / โครงสร้าง",
        s2_bullet_3: "เสริมจมูกโครงสร้างกระดูกอ่อนหลังหู",
        s3_title: "ศัลยกรรมหน้าอก",
        s3_desc: "เสริมหน้าอกพลาสม่าแบบแผลเล็กเป็นพิเศษ โดยใช้ซิลิโคนพรีเมียมแท้แบรนด์ Motiva และ Mentor",
        s3_bullet_1: "เสริมหน้าอกแผลเล็กพิเศษ",
        s3_bullet_2: "แก้ไขหน้าอกหย่อนคล้อยทุกระดับ",
        s3_bullet_3: "ลดขนาดหัวนม / ปานนมให้สมส่วน",
        s4_title: "ดูดไขมันและกระชับสัดส่วน",
        s4_desc: "เทคโนโลยีดูดไขมันขั้นสูงเพื่อลดไขมันส่วนเกินอย่างนุ่มนวล เจ็บน้อย ฟื้นตัวไว",
        s4_bullet_1: "ดูดไขมันหน้าท้องและเอวเอส",
        s4_bullet_2: "ดูดไขมันต้นแขน / ต้นขาให้กระชับ",
        s4_bullet_3: "ผ่าตัดตกแต่งหนังหน้าท้อง (Tummy Tuck)",
        s5_title: "หัตถการความงามไม่ต้องผ่าตัด",
        s5_desc: "ใช้ฟิลเลอร์แท้และโบท็อกซ์ที่ผ่านการรับรองจาก FDA เพื่อลบเลือนริ้วรอยโดยไม่ต้องพักฟื้น",
        s5_bullet_1: "ฉีดฟิลเลอร์ปรับรูปคางและริมฝีปากทรงสวย",
        s5_bullet_2: "ฉีดโบท็อกซ์ลดริ้วรอยหน้าผากและหางตา",
        s5_bullet_3: "ฉีดเมโสคอลลาเจนผิวฉ่ำวาว",
        s6_title: "การดูแลหลังผ่าตัดทางการแพทย์",
        s6_desc: "การดูแลฟื้นฟูหลังผ่าตัดตามมาตรฐานทางการแพทย์ การทำความสะอาดแผล การตัดไหม และการฉายแสงลดบวม",
        s6_bullet_1: "ทำความสะอาดแผลและทำแผลทุกวัน",
        s6_bullet_2: "ฉายแสงชีวภาพเร่งการสมานแผล",
        s6_bullet_3: "นัดติดตามอาการอย่างใกล้ชิดโดยแพทย์",
        s6_link: "ศึกษาขั้นตอนการดูแลหลังผ่าตัด",
        price_tag: "โปร่งใสและน่าเชื่อถือ",
        price_title: "ตารางค่าบริการศัลยกรรมตกแต่ง",
        price_desc: "นพ. ตุง เซือง มอบบริการระดับพรีเมียมในราคาสุทธิแบบเหมาจ่าย โดยไม่มีการเรียกเก็บค่าใช้จ่ายแอบแฝงใดๆ ตลอดระยะเวลาการรักษา",
        filter_all: "บริการทั้งหมด",
        filter_facial: "ศัลยกรรมโครงหน้า",
        filter_body: "ศัลยกรรมหน้าอกและเรือนร่าง",
        table_col_name: "รายการศัลยกรรมความงาม (ระบุวิธีผ่าตัด/วัสดุ)",
        table_col_price: "ค่าใช้จ่าย (USD)",
        price_note: "* หมายเหตุ: ราคาข้างต้นรวมค่าห้องผ่าตัดปลอดเชื้อ ค่าตรวจสุขภาพทั่วไป ค่าระงับความรู้สึกอย่างปลอดภัย ค่ายาหลังผ่าตัด และบริการทำแผลล้างแผลแบบครบวงจรแล้ว โดยไม่มีการบวกเพิ่มใดๆ ทั้งสิ้น",
        book_now_label: "จองคิวทันที",
        form_panel_title: "เนรมิตความงามใหม่ของคุณตั้งแต่วันนี้",
        form_panel_desc: "กรุณาฝากข้อมูลติดต่อของคุณไว้ ผู้ช่วยทางการแพทย์ของ นพ. ตุง เซือง จะติดต่อกลับเพื่อประเมินเบื้องต้นและจัดตารางนัดหมายที่เหมาะสมที่สุดสำหรับคุณ",
        wa_intl_title: "บริการช่วยเหลือระหว่างประเทศผ่าน WhatsApp",
        branches_address: "ฮานอย: 123 Phố Huế, Hai Bà Trưng, ฮานอย<br>โฮจิมินห์: 456 Nguyễn Đình Chiểu, เขต 3, โฮจิมินห์",
        office_hours: "เวลาทำการ: 08:00 น. - 20:00 น. (เปิดบริการทุกวันรวมวันหยุด)",
        dr_footer_p1: "กรุณาจองคิวล่วงหน้าเพื่อหลีกเลี่ยงการรอคิว",
        dr_footer_p2: "สายด่วนพร้อมให้บริการเสมอ",
        form_title: "ข้อมูลลงทะเบียนเพื่อรับคำปรึกษา",
        form_lbl_name: "ชื่อ-นามสกุล *",
        form_lbl_phone: "เบอร์โทรศัพท์ (Zalo/WhatsApp) *",
        form_lbl_service: "เลือกบริการที่สนใจ",
        form_opt_default: "-- เลือกบริการ --",
        form_opt_1: "ศัลยกรรมย้อนวัยผิวหน้า",
        form_opt_2: "ศัลยกรรมตกแต่งตาและชั้นตา",
        form_opt_3: "ศัลยกรรมตกแต่งจมูก",
        form_opt_4: "ศัลยกรรมหน้าอกเทคนิคพลาสม่า",
        form_opt_5: "ดูดไขมันและตกแต่งหน้าท้อง",
        form_opt_6: "หัตถการความงามแบบไม่ต้องผ่าตัด",
        form_lbl_date: "วันที่ต้องการเข้ารับการปรึกษา",
        form_lbl_msg: "ความต้องการหรือคำถามโดยละเอียดถึงคุณหมอ",
        btn_submit: "ส่งข้อมูลลงทะเบียน",
        faq_tag: "บริการช่วยเหลือลูกค้า",
        faq_title: "ไขข้อสงสัยที่พบบ่อย",
        faq_q1: "1. ศัลยกรรมดึงหน้าชั้นลึก (Deep Plane Facelift) ผลลัพธ์อยู่ได้นานกี่ปี?",
        faq_a1: "เทคนิคดึงหน้า Deep Plane ส่งผลโดยตรงถึงชั้น SMAS ซึ่งเป็นกล้ามเนื้อส่วนลึกใต้ผิวหนัง ไม่ใช่แค่การดึงตึงที่ผิวภายนอกเท่านั้น ดังนั้นผลลัพธ์การย้อนวัยจึงยาวนานถึง 20-25 ปี ขึ้นอยู่กับสภาพผิวและการดูแลของแต่ละบุคคล",
        faq_q2: "2. การดูดไขมันหน้าท้องและต้นขาเจ็บมากไหม และเดินได้ปกติเมื่อไหร่?",
        faq_a2: "ด้วยเทคโนโลยีดูดไขมันพลาสม่าและการระงับความรู้สึกรุ่นใหม่ ลูกค้าจะรู้สึกตึงและช้ำเพียงเล็กน้อยคล้ายหลังออกกำลังกายอย่างหนัก โดยทั่วไปหลังผ่านไป 24 ชั่วโมงจะเดินเบาๆ ได้ และกลับไปทำงานออฟฟิศได้ภายใน 3-5 วัน โดยต้องสวมชุดกระชับสัดส่วนอย่างสม่ำเสมอ",
        faq_q3: "3. ทางสถาบันมีนโยบายรับประกันซิลิโคนหน้าอกหรือไม่?",
        faq_a3: "มีค่ะ ซิลิโคนเสริมหน้าอกทั้งหมดที่ใช้ในคลินิกของเรา (Motiva, Mentor) เป็นซิลิโคนพรีเมียมแบรนด์แท้ มีบัตรรับประกันระบบดิจิทัลของทางผู้ผลิตครอบคลุมกรณีซิลิโคนแตกชำrุดหรือเกิดพังผืดรัดตัวตลอดชีวิต",
        footer_intro: "สถาบันศัลยกรรมตกแต่งความงามระดับนานาชาติระดับพรีเมียม มุ่งเน้นการออกแบบสัดส่วนทองคำเพื่อความงามที่เป็นธรรมชาติและหรูหราสำหรับลูกค้าทั่วเอเชีย",
        footer_col_1: "บริการศัลยกรรมหลัก",
        footer_col_2: "ช่องทางลัดช่วยเหลือ",
        footer_col_3: "ช่องทางการติดต่อ",
        footer_policy_1: "นโยบายความเป็นส่วนตัว",
        footer_policy_2: "ข้อตกลงและเงื่อนไขการใช้งาน",
        wa_floating_text: "ปรึกษา WhatsApp",
        gallery_tag: "แกลเลอรีภาพการรักษา",
        gallery_title: "ภาพการผ่าตัดจริง",
        gallery_desc: "ภาพโคลสอัพการผ่าตัดทางคลินิกที่ทำโดย นพ. ตุ่ง เซือง และทีมแพทย์ผู้เชี่ยวชาญในห้องผ่าตัดปลอดเชื้อมาตรฐานสากล",
        gallery_zoom: "ดูรายละเอียด",
        gallery_case1_title: "ห้องผ่าตัดปลอดเชื้อระดับสูงสุด",
        gallery_case1_desc: "ห้องผ่าตัดมาตรฐานการแพทย์สากลระบบปิด ช่วยลดความเสี่ยงของการติดเชื้อได้อย่างดีเยี่ยม",
        gallery_case2_title: "อุปกรณ์ทางการแพทย์เทคโนโลยีสูง",
        gallery_case2_desc: "ใช้มีดผ่าตัดพลาสมาเทคโนโลยีใหม่ล่าสุด ช่วยลดการสูญเสียเลือดและลดอาการบวมช้ำหลังผ่าตัด",
        gallery_case3_title: "แพทย์ออกแบบสัดส่วนทองคำเฉพาะบุคคล",
        gallery_case3_desc: "นพ. ตุ่ง เซือง ประเมินและออกแบบอย่างละเอียดเพื่อให้ได้ผลลัพธ์ที่สวยงามและเป็นธรรมชาติที่สุด",
        gallery_case4_title: "เย็บแผลประณีตลดรอยแผลเป็น",
        gallery_case4_desc: "เทคนิคการเย็บซ่อนแผลขนาดเล็กพิเศษ ช่วยลดรอยแผลหลังจากการฟื้นตัว",
        gallery_case5_title: "ใช้วัสดุทางการแพทย์แท้นำเข้า",
        gallery_case5_desc: "ใช้ซิลิโคน ไหมเย็บ และวัสดุปลูกถ่ายคุณภาพสูงที่ผ่านการรับรองจาก FDA",
        gallery_case6_title: "การดูแลหลังผ่าตัดอย่างใกล้ชิด",
        gallery_case6_desc: "ระบบดูแลหลังผ่าตัดระดับมืออาชีพตลอด 24 ชั่วโมง เพื่อให้คนไข้ฟื้นตัวได้อย่างรวดเร็วและปลอดภัยที่สุด"
    },
    ms: {
        nav_home: "Laman Utama",
        nav_about: "Mengenai Kami",
        nav_services: "Perkhidmatan",
        nav_before_after: "Sebelum & Selepas",
        nav_price: "Senarai Harga",
        nav_faq: "Soalan Lazim",
        nav_contact: "Hubungi Kami",
        book_now: "TEMPAH JANJI TEMU",
        hero_badge: "Akademi Estetik Standard Perubatan Antarabangsa",
        hero_title: "Membentuk <span class='text-transparent bg-clip-text bg-gradient-to-r from-brand-gold to-amber-600 text-glow-gold'>Kecantikan Sempurna</span> <br class='hidden sm:inline'> Dengan Teknologi Moden",
        hero_desc: "Garis wajah dan tubuh yang harmoni serta mewah diukir oleh pakar bedah plastik terkemuka <strong class='text-brand-gold font-bold'>Dr. Tung Duong</strong>. Berkomitmen pada keselamatan mutlak untuk mencapai nisbah keemasan (golden ratio) yang diperibadikan.",
        stats_med: "Standard Perubatan",
        stats_happy: "Klien Berpuas Hati",
        stats_exp: "Tahun Pengalaman",
        btn_price: "Lihat Butiran Harga",
        btn_whatsapp: "Konsultasi WhatsApp Sekarang",
        dr_title: "PAKAR BEDAH PLASTIK",
        dr_quote: "“Mencipta kecantikan tanpa cela dengan dedikasi, etika perubatan dan ketepatan pembedahan.”",
        badge_cert_title: "Kualiti Diluluskan",
        badge_cert_desc: "Sijil Perakuan Kementerian Kesihatan",
        stat_1: "Pembedahan yang Berjaya",
        stat_2: "Ulasan Bintang 5 Klien",
        stat_3: "Tahun Amalan Profesional",
        stat_4: "Penjagaan Pasca-Bedah 24/7",
        about_badge_top: "Estetik High-End",
        about_badge_bottom: "Nisbah keemasan untuk struktur wajah Asia",
        about_tag: "MENGENAI KAMI",
        about_title: "Rawatan Berdasarkan Dedikasi,<br>Etika Perubatan & Nilai Kemanusiaan",
        about_desc: "Di klinik estetik kami, setiap prosedur adalah lebih daripada sekadar rawatan perubatan—ia adalah hasil karya seni arca hidup yang indah. <strong>Dr. Tung Duong</strong> memastikan keharmonian semula jadi yang disesuaikan secara khusus dengan anatomi unik anda, mengelakkan hasil yang kaku dan seragam.",
        feature_1_title: "Bahan Premium",
        feature_1_desc: "Menggunakan bahan implan premium asli yang diimport secara sah dan disahkan selamat oleh FDA.",
        feature_2_title: "Persekitaran Steril",
        feature_2_desc: "Kamar bedah sepenuhnya memenuhi peraturan sanitasi dan keselamatan antarabangsa yang ketat.",
        feature_3_title: "Doktor & Pasukan Perubatan",
        feature_3_desc: "Doktor dan pasukan perubatan pakar melakukan tindakan pembedahan secara langsung kepada pelanggan.",
        feature_4_title: "Waranti Seumur Hidup",
        feature_4_desc: "Garis panduan waranti yang jelas untuk menyokong anda di sepanjang proses pemulihan.",
        dr_position: "Pengarah Perubatan - Pakar Bedah Rekonstruksi & Plastik Termaju",
        ba_tag: "BUKTI NYATA",
        ba_title: "Hasil Transformasi - Sebelum & Selepas",
        ba_desc: "Kualiti terbaik yang dibuktikan oleh perubahan fizikal yang ketara dan kepuasan mutlak pelanggan di bawah kepakaran Dr. Tung Duong.",
        ba_compare_badge: "Maklum Balas Sebenar",
        ba_compare_title: "Ulasan Pelanggan",
        ba_compare_desc: "Mesej sembang tulen daripada pesakit kami berkongsi kepuasan mereka selepas pembedahan dan penjagaan pasca pembedahan.",
        before: "SEBELUM",
        after: "SELEPAS PEMBEDAHAN",
        before_after_label: "SEBELUM & SELEPAS",
        case_1_title: "Deep Plane Facelift",
        case_1_desc: "Menghaluskan garis senyum yang ketara dan menegangkan tisu wajah yang kendur untuk peremajaan maksima.",
        case_2_title: "Peremajaan Wajah Deep Plane",
        case_2_desc: "Meremajakan wajah, menegangkan tisu kendur dan menghaluskan kedutan.",
        case_3_title: "Forehead Lift & Eyebrow Lift",
        case_3_desc: "Menghaluskan kedutan dahi dan mengangkat kening secara semula jadi.",
        case_4_title: "Blefaroplasti Plasma",
        case_4_desc: "Membentuk lipatan kelopak mata yang tajam dan membetulkan kulit kendur.",
        services_tag: "KATEGORI PERKHIDMATAN",
        services_title: "Penyelesaian Estetik Perubatan Komprehensif",
        services_desc: "Menawarkan penyelesaian khusus untuk peremajaan wajah, augmentasi payudara dan kontur tubuh menggunakan teknologi plasma yang canggih.",
        s1_title: "Peremajaan Wajah",
        s1_desc: "Meliputi Deep Plane facelift, neck lift dan pemindahan lemak untuk memadam tanda-tanda penuaan.",
        s1_bullet_1: "Peremajaan Deep Plane Facelift",
        s1_bullet_2: "Pengencangan Leher Anggun",
        s1_bullet_3: "Koreksi Garis Senyum dengan Nano Fat",
        view_price_link: "LIHAT DAFTAR HARGA LENGKAP",
        s2_title: "Estetik Mata & Hidung",
        s2_desc: "Koreksi kelopak mata ganda yang tepat, pembedahan semakan, dan pembentukan hidung struktural yang diperibadikan.",
        s2_bullet_1: "Resculpting Kelopak Mata Plasma",
        s2_bullet_2: "Rhinoplasty Struktural & Semi-Struktural",
        s2_bullet_3: "Koreksi Struktural Tulang Rawan Telinga",
        s3_title: "Prosedur Payudara",
        s3_desc: "Augmentasi payudara Plasma invasif minimum menggunakan implan Motiva dan Mentor premium berlesen.",
        s3_bullet_1: "Augmentasi Invasif Minimum Plasma",
        s3_bullet_2: "Koreksi Ptosis Semua Peringkat (Lift)",
        s3_bullet_3: "Pengecilan Areola & Puting yang Simetri",
        s4_title: "Kontur Tubuh & Liposuction",
        s4_desc: "Penyelesaian liposuction canggih yang direka untuk mengurangkan lemak tubuh secara lembut dengan pemulihan pantas.",
        s4_bullet_1: "Pengecilan Lemak Perut & Pinggul",
        s4_bullet_2: "Pembentukan Lengan & Paha Sasa",
        s4_bullet_3: "Tummy Tuck Lengkap (Abdominoplasti)",
        s5_title: "Filler Tanpa Pembedahan",
        s5_desc: "Menggunakan filler tulen berdaftar FDA dan Botox untuk menghilangkan kerutan tanpa memerlukan tempoh rehat.",
        s5_bullet_1: "Pembentukan Bibir & Dagu yang Menawan",
        s5_bullet_2: "Botox Kedutan Dahi & Sudut Mata",
        s5_bullet_3: "Suntikan Kolagen Revitalisasi Kulit Glowing",
        s6_title: "Rawatan Pasca-Bedah Perubatan",
        s6_desc: "Perkhidmatan pemulihan pasca-bedah komprehensif, pembersihan luka, penyingkiran jahitan, dan terapi bio-light pengurang bengkak.",
        s6_bullet_1: "Pembersihan Luka & Pembalutan Harian",
        s6_bullet_2: "Terapi Cahaya Biologi Mempercepatkan Penyembuhan",
        s6_bullet_3: "Pemantauan Berkala Secara Langsung oleh Dr. Duong",
        s6_link: "PELAJARI PROSEDUR PASCA-BEDAH",
        price_tag: "KETELUSAN & INTEGRITI",
        price_title: "Senarai Tambang Bedah Plastik",
        price_desc: "Dr. Tung Duong memastikan senarai harga yang telus, pakej lengkap tanpa sebarang kos tersembunyi semasa rawatan.",
        filter_all: "Semua Prosedur",
        filter_facial: "Prosedur Wajah",
        filter_body: "Prosedur Tubuh",
        table_col_name: "Prosedur Estetik (Kaedah / Perincian Bahan)",
        table_col_price: "Biaya (USD)",
        price_note: "* Nota: Kos yang dinyatakan termasuk penggunaan bilik bedah steril moden, ujian kesihatan pra-pembedahan, anestesia yang selamat, ubat pasca-pembedahan, dan rawatan penggantian pembalut klinikal. Tiada caj tambahan.",
        book_now_label: "AMANKAN SLOT ANDA",
        form_panel_title: "Wujudkan Penampilan Baru Anda Hari Ini",
        form_panel_desc: "Sila isi butiran anda. Pembantu perubatan kami akan menghubungi anda dalam masa 15 minit untuk memberikan panduan awal dan menempah slot janji temu.",
        wa_intl_title: "Sokongan WhatsApp Antarabangsa",
        branches_address: "Hanoi: Jalan Hue 123, Daerah Hai Ba Trung, Hanoi<br>HCMC: Jalan Nguyen Dinh Chieu 456, Daerah 3, HCMC",
        office_hours: "Waktu Bekerja: 08:00 AM - 20:00 PM (Buka setiap hari termasuk hari Ahad & Cuti Umum)",
        dr_footer_p1: "Daftar terlebih dahulu untuk mengelakkan masa menunggu lama",
        dr_footer_p2: "Talian Kecemasan Aktif 24 Jam",
        form_title: "Borang Permintaan Janji Temu",
        form_lbl_name: "Nama Penuh Anda *",
        form_lbl_phone: "Nombor Telefon / WhatsApp *",
        form_lbl_service: "Prosedur yang Diminati",
        form_opt_default: "-- Pilih Perkhidmatan --",
        form_opt_1: "Peremajaan Kulit Wajah",
        form_opt_2: "Pembedahan Kelopak Mata & Area Mata",
        form_opt_3: "Pembedahan Rhinoplasty (Hidung)",
        form_opt_4: "Augmentasi Payudara Plasma",
        form_opt_5: "Liposuction & Tummy Tuck",
        form_opt_6: "Kecantikan Tanpa Bedah",
        form_lbl_date: "Tarikh Konsultasi yang Diminta",
        form_lbl_msg: "Kebutuhan atau Soalan Perincian untuk Doktor",
        btn_submit: "KIRIM PERMINTAAN RESERVASI",
        faq_tag: "SOALAN & SOKONGAN PELANGGAN",
        faq_title: "Menjawab Soalan Lazim yang Kerap Ditanya",
        faq_q1: "1. Berapa lamakah keputusan Deep Plane Facelift boleh bertahan?",
        faq_a1: "Teknik Deep Plane berfungsi di bawah lapisan otot SMAS terdalam, bukan sekadar menegangkan kulit luar sahaja. Oleh itu, hasil peremajaan wajah boleh bertahan sangat lama, sekitar 20 hingga 25 tahun bergantung kepada penjagaan kulit dan gaya hidup anda.",
        faq_q2: "2. Adakah liposuction menyakitkan, dan bila saya boleh berjalan semula dengan selesa?",
        faq_a2: "Di bawah bantuan anestesia moden, prosedur pembedahan ini langsung tidak menyakitkan. Selepas pembedahan, anda hanya akan merasa sedikit lenguh seperti selepas senaman intensif. Kebiasaannya, dalam tempoh 24 jam anda sudah boleh berjalan perlahan-lahan, dan boleh kembali bekerja pejabat dalam masa 3 hingga 5 hari selepas memakai pakaian pemampatan khas.",
        faq_q3: "3. Adakah implan payudara dilindungi oleh waranti seumur hidup?",
        faq_a3: "Ya. Semua implan payudara yang digunakan di akademi kami (Motiva, Mentor) merupakan peranti gred premium yang dilindungi oleh waranti digital rasmi kilang global seumur hidup terhadap kes kebocoran implan atau kontraktur kapsul.",
        footer_intro: "Klinik Pakar Bedah Plastik Estetik Standard Antarabangsa Premium. Mengukir garis tubuh semula jadi dan mewah yang menepati nisbah keemasan wajah wanita Asia.",
        footer_col_1: "PROSEDUR UTAMA",
        footer_col_2: "PAUTAN PANTAS",
        footer_col_3: "SALURAN HUBUNGAN",
        footer_policy_1: "Dasar Privasi",
        footer_policy_2: "Syarat Penggunaan",
        wa_floating_text: "Konsultasi WhatsApp",
        gallery_tag: "GALERI KLINIKAL",
        gallery_title: "Gambar Pembedahan Sebenar",
        gallery_desc: "Gambar jarak dekat kes pembedahan klinikal yang dilakukan oleh Dr. Tùng Dương dan pasukan perubatan profesional di bilik pembedahan steril standard antarabangsa.",
        gallery_zoom: "Lihat Butiran",
        gallery_case1_title: "Persekitaran pembedahan steril mutlak",
        gallery_case1_desc: "Bilik pembedahan piawaian perubatan antarabangsa moden, mengurangkan risiko jangkitan silang.",
        gallery_case2_title: "Peralatan perubatan teknologi tinggi",
        gallery_case2_desc: "Menggunakan pisau bedah Plasma generasi baharu untuk meminimumkan pendarahan dan mengurangkan bengkak.",
        gallery_case3_title: "Nisbah emas rekaan doktor secara langsung",
        gallery_case3_desc: "Dr. Tùng Dương memeriksa sendiri dan melakar dengan teliti untuk hasil yang paling seimbang dan semula jadi.",
        gallery_case4_title: "Jahitan estetik berketepatan tinggi",
        gallery_case4_desc: "Teknik jahitan halus tersembunyi meminimumkan kesan parut pembedahan selepas sembuh.",
        gallery_case5_title: "Bahan perubatan import tulen",
        gallery_case5_desc: "Menggunakan implan, benang estetik, dan bahan cantuman yang disahkan FDA.",
        gallery_case6_title: "Penjagaan selepas pembedahan yang rapi",
        gallery_case6_desc: "Sistem penjagaan pasca pembedahan 24/7 yang profesional untuk memastikan pemulihan terpantas."
    },
    ph: {
        nav_home: "Home",
        nav_about: "Tungkol sa Amin",
        nav_services: "Mga Serbisyo",
        nav_before_after: "Bago at Pagkatapos",
        nav_price: "Listahan ng Presyo",
        nav_faq: "FAQ",
        nav_contact: "Kontakin Kami",
        book_now: "MAG-BOOK NG APPOINTMENT",
        hero_badge: "Internasyonal na Pamantayang Medikal na Estetikong Academy",
        hero_title: "Paghubog ng <span class='text-transparent bg-clip-text bg-gradient-to-r from-brand-gold to-amber-600 text-glow-gold'>Perpektong Kagandahan</span> <br class='hidden sm:inline'> Gamit ang Makabagong Teknolohiya",
        hero_desc: "Ang mga natural at marangyang hubog na inilikha ng kilalang plastic surgeon na si <strong class='text-brand-gold font-bold'>Dr. Tung Duong</strong>. Nakatuon sa buong kaligtasan upang makamit ang inyong natatanging gold-ratio na mga sukat.",
        stats_med: "Pamantayang Medikal",
        stats_happy: "Masayang Kliyente",
        stats_exp: "Taon ng Karanasan",
        btn_price: "Tingnan ang Detalyadong Presyo",
        btn_whatsapp: "Mag-konsulta sa WhatsApp Ngayon",
        dr_title: "PLASTIC SURGEON",
        dr_quote: "“Gumagawa ng walang-kapintasang kagandahan nang may dedikasyon, etikal na pananaw, at medikal na katumpakan.”",
        badge_cert_title: "Kwalidad na Inaprubahan",
        badge_cert_desc: "Sertipikado ng Ministri ng Kalusugan",
        stat_1: "Mga Matagumpay na Operasyon",
        stat_2: "Mataas na Marka ng Kliyente",
        stat_3: "Taon ng Dedikadong Karanasan",
        stat_4: "24/7 na Propesyonal na Kalinga",
        about_badge_top: "Mataas na Kalidad ng Estetika",
        about_badge_bottom: "Golden ratio para sa istruktura ng mukhang Asyano",
        about_tag: "TUNGKOL SA AMIN",
        about_title: "Kalingang Nakabatay sa Dedikasyon,<br>Etikang Medikal at Makataong Halaga",
        about_desc: "Sa aming clinic, ang bawat pamamaraan ay higit pa sa medikal na paggamot—ito ay isang obra maestra ng buhay na sining. Sinisiguro ni <strong>Dr. Tung Duong</strong> ang natural na armonya na iniangkop sa inyong natatanging anatomiya, iniiwasan ang iisang hitsura para sa lahat.",
        feature_1_title: "Mga Premium na Materyales",
        feature_1_desc: "Gumagamit lamang ng mga de-kalidad na implante na ligtas, imported, at sertipikado ng FDA.",
        feature_2_title: "Sterile na Kapaligiran",
        feature_2_desc: "Ang mga surgical operating room ay sumusunod sa mahigpit na internasyonal na kalinisan at kaligtasan.",
        feature_3_title: "Ang Doktor at Medikal na Koponan",
        feature_3_desc: "Ang doktor at dalubhasang medikal na koponan ang direktang nagsasagawa ng operasyon sa kliyente.",
        feature_4_title: "Panghabambuhay na Serbisyo",
        feature_4_desc: "May malinaw na alituntunin sa serbisyong mag-aalaga sa inyo sa buong panahon ng paggaling.",
        dr_position: "Medikal na Direktor - Dalubhasa sa Advanced Plastic & Reconstruction Surgery",
        ba_tag: "KATOTOHANANG KATIBAYAN",
        ba_title: "Kamangha-manghang Resulta - Bago at Pagkatapos",
        ba_desc: "Katangi-tanging kalidad na pinatutunayan ng mga pisikal na pagbabago at lubos na kasiyahan ng libu-libong kliyente sa ilalim ng pamamahala ni Dr. Tung Duong.",
        ba_compare_badge: "Totoong Feedback",
        ba_compare_title: "Mga Ulat ng Kliyente",
        ba_compare_desc: "Tunay na mga mensahe mula sa aming mga pasyente na nagbabahagi ng kanilang kasiyahan pagkatapos ng operasyon at pangangalaga.",
        before: "BAGO",
        after: "PAGKATAPOS NG OPERASYON",
        before_after_label: "BAGO & PAGKATAPOS",
        case_1_title: "Deep Plane Facelift",
        case_1_desc: "Inaalis ang malalalim na kulubot sa pisngi at itinataas ang lumalaylay na balat para sa mukhang bata.",
        case_2_title: "Deep Plane Facial Rejuvenation",
        case_2_desc: "Pagpapabata ng mukha, pag-angat ng laylay na balat at pagpapakinis ng kulubot.",
        case_3_title: "Forehead Lift & Eyebrow Lift",
        case_3_desc: "Pagtanggal ng kulubot sa noo at pag-angat ng kilay sa likas na paraan.",
        case_4_title: "Plasma Blepharoplasty",
        case_4_desc: "Paglikha ng magandang tupi sa mata at pagtatama ng nakalaylay na balat.",
        services_tag: "MGA KATEGORYA NG SERBISYO",
        services_title: "Komprehensibong Estetikong Solusyon",
        services_desc: "Nag-aalok ng mga angkop na solusyon para sa pagpapabata ng mukha, pagpapaganda ng dibdib, at paghubog ng katawan gamit ang advanced plasma technology.",
        s1_title: "Pagpapabata ng Mukha",
        s1_desc: "Kabilang ang Deep Plane facelift, neck lift, at fat transfer upang burahin ang mga marka ng edad sa mukha.",
        s1_bullet_1: "Deep Plane Facelift Rejuvenation",
        s1_bullet_2: "Eleganteng Pag-angat ng Balat sa Leeg",
        s1_bullet_3: "Nano Fat Smile Line Correction",
        view_price_link: "TINGNAN ANG LAHAT NG PRESYO",
        s2_title: "Estetika sa Mata at Ilong",
        s2_desc: "Tumpak na pag-aayos ng kelopak ng mata, pagrerebisa ng mga lumang gawa, at structural na pagpapaganda ng ilong.",
        s2_bullet_1: "Plasma Eyelid Re-sculpting",
        s2_bullet_2: "Structural at Semi-Structural Rhinoplasty",
        s2_bullet_3: "Ear Cartilage Structural Correction",
        s3_title: "Prosedura sa Dibdib",
        s3_desc: "Ligtas na pagpapalaki ng dibdib gamit ang mga de-kalidad na implant tulad ng Motiva at Mentor.",
        s3_bullet_1: "Plasma Minimally Invasive Augmentation",
        s3_bullet_2: "Pag-angat ng Lumalaylay na Dibdib sa Anumang Antas",
        s3_bullet_3: "Paliit at Pag-aayos ng Areola at Putong",
        s4_title: "Pagbawas ng Taba at Paghubog",
        s4_desc: "Makabagong paraan ng liposuction upang ligtas na matanggal ang labis na taba na may mabilis na paggaling.",
        s4_bullet_1: "Pagbawas ng Taba sa Buong Tiyan at Baywang",
        s4_bullet_2: "Paghubog ng Braso at Hita para Maging Siksik",
        s4_bullet_3: "Kumpletong Tummy Tuck (Abdominoplasty)",
        s5_title: "Mga Di-Surgical na Solusyon",
        s5_desc: "Paggamit ng orihinal na FDA-approved fillers at Botox para pakinisin ang mukha nang walang downtime.",
        s5_bullet_1: "Pagpapaganda ng Hugis ng Labi at Baba",
        s5_bullet_2: "Botox para sa Noo at Kulubot sa Mata",
        s5_bullet_3: "Collagen Injection para sa Makintab na Balat",
        s6_title: "Medikal na Pangangalaga Pagkatapos",
        s6_desc: "Komprehensibong paggabay sa paggaling, paglilinis ng sugat, pagtanggal ng tahi, at bio-light therapy laban sa pamamaga.",
        s6_bullet_1: "Araw-araw na Paglilinis at Paggamot sa Sugat",
        s6_bullet_2: "Bio-light Healing Acceleration Therapy",
        s6_bullet_3: "Regular na Pagsubaybay sa Paggaling ni Dr. Duong",
        s6_link: "ALAMIN ANG MGA PROSEDURA SA PAGGALING",
        price_tag: "KATAPATAN AT INTEGRIDAD",
        price_title: "Listahan ng Presyo sa Pagpapaganda",
        price_desc: "Tinitiyak ni Dr. Tung Duong ang malinaw at kumpletong presyo na walang anumang nakatagong bayarin habang nagpapagamot.",
        filter_all: "Lahat ng Prosedura",
        filter_facial: "Mga Prosedura sa Mukha",
        filter_body: "Mga Prosedura sa Katawan",
        table_col_name: "Estetikong Pamamaraan (Paraan / Detalye ng Materyal)",
        table_col_price: "Halaga (USD)",
        price_note: "* Tandaan: Kasama na sa mga presyo ang paggamit ng modernong sterile operating room, mga pagsusuri sa kalusugan bago operahan, ligtas na pampatulog, gamot pagkatapos ng operasyon, at pagpapalit ng benda. Walang karagdagang bayad.",
        book_now_label: "I-RESERBA ANG INYONG SLOT",
        form_panel_title: "Simulan ang Inyong Bagong Kagandahan Ngayon",
        form_panel_desc: "Iwanan ang inyong mga detalye. Tatawag ang aming mga medikal na katulong sa loob ng 15 minuto upang gabayan kayo at i-book ang inyong appointment.",
        wa_intl_title: "Suporta sa WhatsApp sa Buong Mundo",
        branches_address: "Hanoi: 123 Hue Street, Hai Ba Trung District, Hanoi<br>HCMC: 456 Nguyen Dinh Chieu, District 3, HCMC",
        office_hours: "Oras ng Trabaho: 08:00 AM - 20:00 PM (Bukas araw-araw kabilang ang Linggo at Holiday)",
        dr_footer_p1: "Mag-book nang maaga upang maiwasan ang mahabang pila",
        dr_footer_p2: "Aktibong Emergency Hotline 24/7",
        form_title: "Form sa Paghiling ng Appointment",
        form_lbl_name: "Inyong Buong Pangalan *",
        form_lbl_phone: "Numero ng Telepono / WhatsApp *",
        form_lbl_service: "Serbisyong Ninanais",
        form_opt_default: "-- Pumili ng Serbisyong Ninanais --",
        form_opt_1: "Pagpapabata ng Mukha",
        form_opt_2: "Pag-aayos ng Mata at Kelopak",
        form_opt_3: "Pagpapaganda ng Hugis ng Ilong",
        form_opt_4: "Plasma Breast Augmentation",
        form_opt_5: "Liposuction at Tummy Tuck",
        form_opt_6: "Di-Surgical na Pagpapaganda",
        form_lbl_date: "Ninanais na Araw ng Konsultasyon",
        form_lbl_msg: "Mga Kahilingan o Detalyadong Tanong para kay Dr. Duong",
        btn_submit: "IPADALA ANG REQUEST SA RESERBASYON",
        faq_tag: "SERBISYO AT TULONG SA KLIYENTE",
        faq_title: "Sagot sa mga Madalas Itanong",
        faq_q1: "1. Gaano katagal bago mawala ang epekto ng Deep Plane Facelift?",
        faq_a1: "Ang Deep Plane technique ay gumagana sa ilalim ng SMAS muscle layer, hindi lang sa pagbabanat ng balat. Kaya naman ang resulta ay tumatagal ng 20 hanggang 25 taon, depende sa inyong paraan ng pamumuhay at pangangalaga sa balat.",
        faq_q2: "2. Masakit ba ang liposuction, at gaano kabilis ako makakalakad nang maayos?",
        faq_a2: "Dahil sa modernong pampamanhid, walang nararamdamang sakit habang isinasagawa ang operasyon. Pagkatapos nito, makakaramdam lamang ng kaunting ngalay na parang galing sa matinding ehersisyo. Kadalasan, nakakalakad na nang dahan-dahan sa loob ng 24 oras, at nakakabalik sa trabaho sa opisina pagkalipas ng 3 hanggang 5 araw habang nakasuot ng compression garments.",
        faq_q3: "3. May panghabambuhay bang warranty para sa breast implant?",
        faq_a3: "Oo. Lahat ng implante na ginagamit sa aming academy (Motiva, Mentor) ay may kasamang digital warranty card mula sa gumawa na may panghabambuhay na bisa laban sa pagkasira o capsular contracture sa buong mundo.",
        footer_intro: "Mataas na Kalidad ng Estetikong Clinic na may Internasyonal na Pamantayan. Humuhubog ng natural at marangyang anyo ayon sa gold-ratio ng mukhang Asyano.",
        footer_col_1: "MGA PANGUNAHING SERBISYO",
        footer_col_2: "MABILIS NA ACCESS",
        footer_col_3: "MGA DAPAT KONTAKIN",
        footer_policy_1: "Patakaran sa Pribado",
        footer_policy_2: "Mga Tuntunin sa Paggamit",
        wa_floating_text: "WhatsApp Consult",
        gallery_tag: "KLINIKAL NA GALERY",
        gallery_title: "Mga Larawan ng Tunay na Operasyon",
        gallery_desc: "Mga close-up na larawan ng mga klinikal na operasyon na direktang isinagawa ni Dr. Tùng Dương at ng propesyonal na medikal na koponan sa isang sterile na silid-operasyon na may internasyonal na pamantayan.",
        gallery_zoom: "Tingnan ang Detalye",
        gallery_case1_title: "Ganap na sterile na kapaligiran ng operasyon",
        gallery_case1_desc: "Modernong saradong silid-operasyon na may pamantayang medikal na internasyonal, binabawasan ang panganib ng impeksyon.",
        gallery_case2_title: "Mataas na teknolohiyang kagamitang medikal",
        gallery_case2_desc: "Paggamit ng bagong henerasyon ng Plasma surgical knife upang mabawasan ang pagdurugo at mapabilis ang pagkawala ng pamamaga.",
        gallery_case3_title: "Golden ratio na direktang dinisenyo ng doktor",
        gallery_case3_desc: "Direktang sinusuri at maingat na sinusukat ni Dr. Tùng Dương upang makamit ang pinakabalanse at likas na resulta.",
        gallery_case4_title: "Tiyak na estetikong pagtatahi",
        gallery_case4_desc: "Ang ultra-fine suturing technique ay nagpapababa ng mga bakas ng operasyon pagkatapos gumaling.",
        gallery_case5_title: "Tunay at imported na mga materyal na medikal",
        gallery_case5_desc: "Gumagamit ng mga FDA-certified na implant, estetikong sinulid, at mga materyales sa pag-graft.",
        gallery_case6_title: "Maingat na pag-aalaga pagkatapos ng operasyon",
        gallery_case6_desc: "Propesyonal na 24/7 na pangangalaga pagkatapos ng operasyon upang masubaybayan ang pinakamabilis na paggaling."
    }
};

        // Fallbacks for other languages to English to keep dictionary lightweight
        //DICTIONARY.id = DICTIONARY.en;
        //DICTIONARY.th = DICTIONARY.en;
        //DICTIONARY.ms = DICTIONARY.en;
        //DICTIONARY.ph = DICTIONARY.en; 

        let activeLang = 'vi';
        let currentCategory = 'all';

        // Tự động nhận diện ngôn ngữ thiết bị của người dùng khi load trang
        function autoDetectDeviceLanguage() {
            try {
                // Đọc cài đặt ngôn ngữ trình duyệt
                const deviceLang = (navigator.language || navigator.userLanguage || 'vi').toLowerCase();
                const prefix = deviceLang.split('-')[0];
                
                const supportedLanguages = ['vi', 'en', 'zh', 'id', 'th', 'ms', 'ph'];
                if (supportedLanguages.includes(prefix)) {
                    return prefix;
                }
                
                // Tiếng tagalog / filipino thường trả về tl hoặc fil, map sang ph
                if (prefix === 'fil' || prefix === 'tl') {
                    return 'ph';
                }
            } catch (e) {
                console.error("Lỗi tự động nhận diện ngôn ngữ:", e);
            }
            return 'vi'; // Default fallback
        }

        // Thiết lập ngôn ngữ hoạt động và cập nhật giao diện trực quan
        function setLanguage(lang) {
            activeLang = lang;
            
            // Highlight cờ đang được chọn
            document.querySelectorAll('.flag-btn, button[id^="flag-"]').forEach(btn => {
                btn.classList.remove('border-brand-gold', 'shadow-md', 'scale-110');
                btn.classList.add('border-transparent');
            });

            const activeFlagBtn = document.getElementById(`flag-${lang}`);
            if (activeFlagBtn) {
                activeFlagBtn.classList.remove('border-transparent');
                activeFlagBtn.classList.add('border-brand-gold', 'shadow-md', 'scale-110');
            }

            // Thực hiện dịch tất cả các thẻ có thuộc tính data-i18n
            const dict = DICTIONARY[lang] || DICTIONARY.vi;
            document.querySelectorAll('[data-i18n]').forEach(element => {
                const key = element.getAttribute('data-i18n');
                if (dict[key]) {
                    // Nếu là thẻ input hoặc textarea có placeholder, dịch placeholder
                    if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
                        element.placeholder = dict[key];
                    } else {
                        element.innerHTML = dict[key];
                    }
                }
            });

            // Tải lại bảng giá theo ngôn ngữ (các mô tả đi kèm)
            applyFilterAndSearch();
        }